/** Копия секции «Как проходит перенос». Один файл на секцию — три языка рядом. */
export const brief = {
  ru: {
    stepsEyebrow: 'Как проходит перенос',
    step1Title: 'Подключение',
    step1Text: 'TLS и авторизация проверяются отдельно, поэтому ошибка называет причину, а не «не удалось подключиться».',
    step2Title: 'Замер',
    step2Text: 'Дерево папок, число писем и объём — до того, как что-то начнёт копироваться.',
    step3Title: 'Копирование',
    step3Text: 'Папка за папкой, с журналом. Повторный запуск докидывает недостающее и не создаёт дублей.',
    step4Title: 'Сверка',
    step4Text: 'Отчёт со счётчиками с обеих сторон и списком пропущенных писем с причиной.',
    factsEyebrow: 'Что происходит с данными',
    fact1Title: 'Источник не изменяется',
    fact1Text: 'Базовый режим только копирует. Удаление в назначении — отдельная опция за подтверждением.',
    fact2Title: 'Открытый пароль не сохраняется',
    fact2Text: 'HTTPS до сайта, дальше учётные данные шифруются для воркера и хранятся зашифрованным пакетом; расшифровка — в памяти на время задания.',
    fact3Title: 'Письма не остаются у нас',
    fact3Text: 'Сообщения идут потоком со старого сервера на новый, копии не создаётся.',
    fact4Title: 'Можно не отдавать пароль вовсе',
    fact4Text: 'Настольный клиент и Docker работают без нашей инфраструктуры.',
    securityLink: 'Полная модель безопасности',
  },
  en: {
    stepsEyebrow: 'How a transfer runs',
    step1Title: 'Connection',
    step1Text: 'TLS and authentication are checked separately, so an error tells you the actual cause instead of “could not connect”.',
    step2Title: 'Size check',
    step2Text: 'Folder tree, message counts and total volume — before anything starts copying.',
    step3Title: 'Copying',
    step3Text: 'Folder by folder, with a live log. Running it again picks up what is missing and creates no duplicates.',
    step4Title: 'Reconciliation',
    step4Text: 'A report with counts from both sides and a list of skipped messages with the reason for each.',
    factsEyebrow: 'What happens to your data',
    fact1Title: 'The source is left untouched',
    fact1Text: 'The default mode only copies. Deleting on the destination is a separate option behind a confirmation.',
    fact2Title: 'Plaintext passwords are never stored',
    fact2Text: 'HTTPS to the site, then credentials are encrypted for the worker and held as an encrypted blob; they are decrypted in memory only for the duration of the job.',
    fact3Title: 'Your mail does not stay with us',
    fact3Text: 'Messages stream straight from the old server to the new one — no copy is kept.',
    fact4Title: 'You can withhold the password entirely',
    fact4Text: 'The desktop client and the Docker image run without our infrastructure.',
    securityLink: 'Full security model',
  },
  uk: {
    stepsEyebrow: 'Як проходить перенесення',
    step1Title: 'Підключення',
    step1Text: 'TLS і авторизація перевіряються окремо, тож помилка називає причину, а не «не вдалося підключитися».',
    step2Title: 'Замір',
    step2Text: 'Дерево папок, кількість листів і обсяг — ще до того, як щось почне копіюватися.',
    step3Title: 'Копіювання',
    step3Text: 'Папка за папкою, із журналом. Повторний запуск додає те, чого бракує, і не створює дублікатів.',
    step4Title: 'Звірка',
    step4Text: 'Звіт із лічильниками з обох боків і переліком пропущених листів із причиною.',
    factsEyebrow: 'Що відбувається з даними',
    fact1Title: 'Джерело не змінюється',
    fact1Text: 'Базовий режим лише копіює. Видалення у призначенні — окрема опція за підтвердженням.',
    fact2Title: 'Відкритий пароль не зберігається',
    fact2Text: 'HTTPS до сайту, далі облікові дані шифруються для воркера й зберігаються зашифрованим пакетом; розшифрування — у пам’яті на час завдання.',
    fact3Title: 'Листи не лишаються в нас',
    fact3Text: 'Повідомлення йдуть потоком зі старого сервера на новий, копія не створюється.',
    fact4Title: 'Пароль можна не віддавати взагалі',
    fact4Text: 'Настільний клієнт і Docker працюють без нашої інфраструктури.',
    securityLink: 'Повна модель безпеки',
  },
} as const;
