/** Копия секции «Калькулятор». Один файл на секцию — три языка рядом.
 * Строки, которые подставляет императивный код, лежат в calculator-runtime.ts. */
export const calculator = {
  ru: {
    eyebrow: 'Оценка до запуска',
    h2a: 'Сколько это займёт ',
    h2b: 'и во сколько обойдётся.',
    lede: 'Скорость переноса определяет не ваш канал, а лимиты провайдера-источника. Gmail отдаёт около 2.5 ГБ в сутки и никакие настройки этого не изменят — поэтому время лучше узнать заранее, а не на третий день.',
    sizeLabel: 'Объём ящика',
    sizeValue: '12 ГБ',
    srcLabel: 'Откуда переносим',
    src: {
      gmail: { name: 'Gmail', rate: '~2.5 ГБ / сутки' },
      m365: { name: 'Microsoft 365', rate: '~0.5 ГБ / час' },
      yandex: { name: 'Яндекс', rate: '~1.4 ГБ / час' },
      icloud: { name: 'iCloud', rate: '~0.8 ГБ / час' },
      own: { name: 'Свой сервер', rate: '~4.5 ГБ / час' },
    },
    timeLabel: 'Ориентировочное время',
    rowSource: 'Источник',
    rowRate: 'Эффективная скорость',
    rowMsgs: 'Писем примерно',
    rowPlan: 'Тариф по объёму',
    sourceDefault: 'Gmail',
    note: 'Оценка, а не гарантия: реальная скорость зависит от размера писем, числа папок и текущей загрузки провайдера. Мелкие письма едут медленнее крупных — накладные расходы на каждое сообщение одинаковы.',
  },
  en: {
    eyebrow: 'Estimate before you start',
    h2a: 'How long it takes ',
    h2b: 'and what it costs.',
    lede: 'Transfer speed is set by the limits of the source provider, not by your connection. Gmail hands over about 2.5 GB a day and no setting changes that — so it is better to know the timeline up front than on day three.',
    sizeLabel: 'Mailbox size',
    sizeValue: '12 GB',
    srcLabel: 'Moving from',
    src: {
      gmail: { name: 'Gmail', rate: '~2.5 GB / day' },
      m365: { name: 'Microsoft 365', rate: '~0.5 GB / hour' },
      yandex: { name: 'Yandex', rate: '~1.4 GB / hour' },
      icloud: { name: 'iCloud', rate: '~0.8 GB / hour' },
      own: { name: 'Own server', rate: '~4.5 GB / hour' },
    },
    timeLabel: 'Estimated time',
    rowSource: 'Source',
    rowRate: 'Effective speed',
    rowMsgs: 'Messages, roughly',
    rowPlan: 'Plan for this size',
    sourceDefault: 'Gmail',
    note: 'An estimate, not a guarantee: real speed depends on message size, how many folders there are and how busy the provider is right now. Small messages move slower than large ones — the per-message overhead is the same either way.',
  },
  uk: {
    eyebrow: 'Оцінка перед запуском',
    h2a: 'Скільки це займе ',
    h2b: 'і скільки коштуватиме.',
    lede: 'Швидкість перенесення визначає не ваш канал, а ліміти провайдера-джерела. Gmail віддає близько 2.5 ГБ на добу, і жодні налаштування цього не змінять — тому час краще дізнатися заздалегідь, а не на третій день.',
    sizeLabel: 'Обсяг скриньки',
    sizeValue: '12 ГБ',
    srcLabel: 'Звідки переносимо',
    src: {
      gmail: { name: 'Gmail', rate: '~2.5 ГБ / добу' },
      m365: { name: 'Microsoft 365', rate: '~0.5 ГБ / год' },
      yandex: { name: 'Яндекс', rate: '~1.4 ГБ / год' },
      icloud: { name: 'iCloud', rate: '~0.8 ГБ / год' },
      own: { name: 'Власний сервер', rate: '~4.5 ГБ / год' },
    },
    timeLabel: 'Орієнтовний час',
    rowSource: 'Джерело',
    rowRate: 'Ефективна швидкість',
    rowMsgs: 'Листів приблизно',
    rowPlan: 'Тариф за обсягом',
    sourceDefault: 'Gmail',
    note: 'Оцінка, а не гарантія: реальна швидкість залежить від розміру листів, кількості папок і поточного навантаження провайдера. Дрібні листи їдуть повільніше за великі — накладні витрати на кожен лист однакові.',
  },
} as const;
