/** Копия секции «Калькулятор». Один файл на секцию — три языка рядом.
 * Строки, которые подставляет императивный код, лежат в calculator-runtime.ts. */
export const calculator = {
  ru: {
    eyebrow: 'Оценка до запуска',
    h2a: 'Сколько это займёт ',
    h2b: 'и во сколько обойдётся.',
    lede: 'Скорость определяет не ваш канал, а лимиты обеих сторон: перенос идёт со скоростью медленной. У Gmail это видно лучше всего — он отдаёт 2500 МБ в сутки, а принимает всего 500, и перенос в него идёт впятеро дольше, чем из него.',
    sizeLabel: 'Объём ящика',
    sizeValue: '12 ГБ',
    srcLabel: 'Откуда переносим',
    dstLabel: 'Куда переносим',
    src: {
      gmail: { name: 'Gmail', rate: '2.5 ГБ / сутки', basis: 'документировано' },
      m365: { name: 'Microsoft 365', rate: '~0.5 ГБ / час', basis: 'оценка' },
      yandex: { name: 'Яндекс', rate: '~1.4 ГБ / час', basis: 'оценка' },
      icloud: { name: 'iCloud', rate: '~0.8 ГБ / час', basis: 'оценка' },
      own: { name: 'Свой сервер', rate: '~4.5 ГБ / час', basis: 'оценка' },
    },
    dst: {
      own: { name: 'Свой сервер', rate: '~4.5 ГБ / час', basis: 'оценка' },
      gmail: { name: 'Gmail', rate: '500 МБ / сутки', basis: 'документировано' },
      m365: { name: 'Microsoft 365', rate: '~0.5 ГБ / час', basis: 'оценка' },
      yandex: { name: 'Яндекс', rate: '~1.4 ГБ / час', basis: 'оценка' },
      icloud: { name: 'iCloud', rate: '~0.8 ГБ / час', basis: 'оценка' },
    },
    timeLabel: 'Ориентировочное время',
    rowSource: 'Источник',
    rowDest: 'Назначение',
    barSource: 'отдаёт',
    barDest: 'принимает',
    rowRate: 'Эффективная скорость',
    rowMsgs: 'Писем примерно',
    rowPlan: 'Тариф по объёму',
    sourceDefault: 'Gmail',
    note: 'Оценка, а не гарантия: реальная скорость зависит от размера писем, числа папок и текущей загрузки провайдера. Мелкие письма едут медленнее крупных — накладные расходы на каждое сообщение одинаковы.',
  },
  en: {
    eyebrow: 'Estimate before you start',
    h2a: 'How long it takes ',
    h2b: 'and what it costs.',
    lede: 'Speed is set by the limits on both sides, not by your connection: a migration runs at the pace of the slower one. Gmail shows it best — it hands over 2500 MB a day but accepts only 500, so moving into it takes five times longer than moving out.',
    sizeLabel: 'Mailbox size',
    sizeValue: '12 GB',
    srcLabel: 'Moving from',
    dstLabel: 'Moving to',
    src: {
      gmail: { name: 'Gmail', rate: '2.5 GB / day', basis: 'documented' },
      m365: { name: 'Microsoft 365', rate: '~0.5 GB / hour', basis: 'estimate' },
      yandex: { name: 'Yandex', rate: '~1.4 GB / hour', basis: 'estimate' },
      icloud: { name: 'iCloud', rate: '~0.8 GB / hour', basis: 'estimate' },
      own: { name: 'Own server', rate: '~4.5 GB / hour', basis: 'estimate' },
    },
    dst: {
      own: { name: 'Own server', rate: '~4.5 GB / hour', basis: 'estimate' },
      gmail: { name: 'Gmail', rate: '500 MB / day', basis: 'documented' },
      m365: { name: 'Microsoft 365', rate: '~0.5 GB / hour', basis: 'estimate' },
      yandex: { name: 'Yandex', rate: '~1.4 GB / hour', basis: 'estimate' },
      icloud: { name: 'iCloud', rate: '~0.8 GB / hour', basis: 'estimate' },
    },
    timeLabel: 'Estimated time',
    rowSource: 'Source',
    rowDest: 'Destination',
    barSource: 'sends',
    barDest: 'accepts',
    rowRate: 'Effective speed',
    rowMsgs: 'Messages, roughly',
    rowPlan: 'Plan for this size',
    sourceDefault: 'Gmail',
    note: 'An estimate, not a guarantee: real speed depends on message size, how many folders there are and how busy the provider is right now. Small messages move slower than large ones — the per-message overhead is the same either way.',
  },
  uk: {
    eyebrow: 'Оцінка перед запуском',
    h2a: 'Скільки це займе ',
    h2b: 'і скільки коштуватиме.',
    lede: 'Швидкість визначає не ваш канал, а ліміти обох сторін: перенесення йде зі швидкістю повільнішої. У Gmail це видно найкраще — він віддає 2500 МБ на добу, а приймає лише 500, тож перенесення в нього триває вп’ятеро довше.',
    sizeLabel: 'Обсяг скриньки',
    sizeValue: '12 ГБ',
    srcLabel: 'Звідки переносимо',
    dstLabel: 'Куди переносимо',
    src: {
      gmail: { name: 'Gmail', rate: '2.5 ГБ / добу', basis: 'задокументовано' },
      m365: { name: 'Microsoft 365', rate: '~0.5 ГБ / год', basis: 'оцінка' },
      yandex: { name: 'Яндекс', rate: '~1.4 ГБ / год', basis: 'оцінка' },
      icloud: { name: 'iCloud', rate: '~0.8 ГБ / год', basis: 'оцінка' },
      own: { name: 'Власний сервер', rate: '~4.5 ГБ / год', basis: 'оцінка' },
    },
    dst: {
      own: { name: 'Власний сервер', rate: '~4.5 ГБ / год', basis: 'оцінка' },
      gmail: { name: 'Gmail', rate: '500 МБ / добу', basis: 'задокументовано' },
      m365: { name: 'Microsoft 365', rate: '~0.5 ГБ / год', basis: 'оцінка' },
      yandex: { name: 'Яндекс', rate: '~1.4 ГБ / год', basis: 'оцінка' },
      icloud: { name: 'iCloud', rate: '~0.8 ГБ / год', basis: 'оцінка' },
    },
    timeLabel: 'Орієнтовний час',
    rowSource: 'Джерело',
    rowDest: 'Призначення',
    barSource: 'віддає',
    barDest: 'приймає',
    rowRate: 'Ефективна швидкість',
    rowMsgs: 'Листів приблизно',
    rowPlan: 'Тариф за обсягом',
    sourceDefault: 'Gmail',
    note: 'Оцінка, а не гарантія: реальна швидкість залежить від розміру листів, кількості папок і поточного навантаження провайдера. Дрібні листи їдуть повільніше за великі — накладні витрати на кожен лист однакові.',
  },
} as const;
