/** Данные справочника провайдеров, которые императивный код (lib/guides.ts)
 * подставляет в панель: название, вступление, таблица подключения, шаги,
 * подводные камни и эквивалентная команда imapsync.
 * Разметка секции переведена отдельно — в provider-guides.ts.
 *
 * Ключи провайдеров (gmail, m365, …) совпадают с data-pv у кнопок и не
 * переводятся. Второй элемент в `warns` — флаг из исходного макета. */
export const guidesRuntime = {
  ru: {
    stepsTitle: 'Пошагово',
    warnsTitle: 'Подводные камни',
    cmdCaption: 'Эквивалент в imapsync — то, что MoveMailbox соберёт за вас',
    pv: {
      gmail: {
        n: 'Gmail / Google Workspace',
        intro: 'Самый частый источник и самое частое место, где перенос спотыкается. Gmail не хранит папки — он хранит ярлыки, поэтому одно письмо видно сразу в нескольких «папках», и наивный перенос легко создаёт дубликаты.',
        conn: [['Сервер', 'imap.gmail.com'], ['Порт', '993 · SSL/TLS'], ['Логин', 'полный адрес'], ['Пароль', 'пароль приложения']],
        steps: ['В аккаунте Google включите двухэтапную аутентификацию — без неё пароли приложений недоступны.',
          'Откройте раздел «Пароли приложений», создайте пароль с именем MoveMailbox и скопируйте 16 символов.',
          'В Gmail: Настройки → Пересылка и POP/IMAP → «Включить IMAP» → Сохранить.',
          'В поле пароля вставьте пароль приложения без пробелов. Обычный пароль аккаунта работать не будет.',
          'Для Google Workspace убедитесь, что администратор не выключил IMAP для организации.'],
        warns: [['<b>Ярлык «Вся почта»</b> — <code>[Gmail]/All Mail</code> содержит копии всех писем. Если не исключить его, объём удваивается и в назначение приезжают дубли.', 1],
          ['<b>Лимит на объём</b> — Gmail отдаёт примерно 2 500 МБ в сутки на ящик через IMAP. Большой архив едет несколько дней, это нормально, а не поломка.', 1],
          ['<b>Корзина и Спам</b> обычно переносить не нужно: снимите галочки на <code>[Gmail]/Trash</code> и <code>[Gmail]/Spam</code>.', 1],
          ['<b>Приостановка</b> — при слишком агрессивной скорости Google временно блокирует IMAP на несколько часов. Мы держим один поток и паузы между папками.', 1]],
        cmd: 'imapsync \\\n  --host1 imap.gmail.com --port1 993 --ssl1 \\\n  --user1 anna@old.com --passfile1 /run/secrets/p1 \\\n  --host2 imap.new.com --port2 993 --ssl2 \\\n  --user2 anna@new.com --passfile2 /run/secrets/p2 \\\n  --exclude "^\\[Gmail\\]/All Mail$" --exclude "^\\[Gmail\\]/Spam$" \\\n  --automap --dry',
      },
      m365: {
        n: 'Microsoft 365 / Exchange Online',
        intro: 'Самый денежный маршрут и самый требовательный. Microsoft отключил basic authentication для Exchange Online, поэтому обычная пара «логин + пароль» на большинстве тенантов уже не проходит — нужен OAuth 2.0 (XOAUTH2).',
        conn: [['Сервер', 'outlook.office365.com'], ['Порт', '993 · SSL/TLS'], ['Логин', 'UPN пользователя'], ['Аутентификация', 'OAuth 2.0 / XOAUTH2']],
        steps: ['Убедитесь, что у пользователя включён IMAP: Exchange admin center → Получатели → Почтовые ящики → Управление email-приложениями.',
          'Если basic auth отключён (по умолчанию так) — авторизуйтесь через OAuth: MoveMailbox запросит доступ и получит токен, пароль вводить не нужно.',
          'Для тенанта, где OAuth ещё не согласован, администратор даёт согласие один раз на приложение с правом <code>IMAP.AccessAsUser.All</code>.',
          'Альтернатива для одиночного ящика с MFA — пароль приложения, но он доступен не во всех тенантах и Microsoft его сворачивает.',
          'Проверьте лимит подключений: 20 одновременных IMAP-сессий на ящик, иначе сервер начнёт рвать соединения.'],
        warns: [['<b>Throttling</b> — Exchange Online режет скорость при интенсивной записи. На больших ящиках закладывайте время, а не увеличивайте параллелизм.', 1],
          ['<b>Спецпапки</b> — Archive, Conversation History и Notes переносятся как обычные IMAP-папки, но их содержимое в Outlook может выглядеть иначе.', 1],
          ['<b>Размер письма</b> — по умолчанию 35 МБ на входящее. Письма с большими вложениями будут пропущены и попадут в отчёт.', 1],
          ['<b>Личные архивы</b> (In-Place Archive) через IMAP не видны вообще — это отдельное хранилище, нужен другой инструмент.', 1]],
        cmd: 'imapsync \\\n  --host1 imap.old.com --port1 993 --ssl1 --user1 anna@old.com \\\n  --host2 outlook.office365.com --port2 993 --ssl2 \\\n  --user2 anna@company.com \\\n  --oauthaccesstoken2 /run/secrets/o365.token \\\n  --office2 --automap --useuid',
      },
      outlook: {
        n: 'Outlook.com / Hotmail / Live',
        intro: 'Личные ящики Microsoft. Хост тот же, что у корпоративного 365, но пароль приложения здесь ещё поддерживается — при включённой двухшаговой проверке это самый простой путь.',
        conn: [['Сервер', 'outlook.office365.com'], ['Порт', '993 · SSL/TLS'], ['Логин', 'полный адрес'], ['Пароль', 'пароль приложения']],
        steps: ['Включите двухшаговую проверку в настройках безопасности учётной записи Microsoft.',
          'Создайте пароль приложения в разделе «Дополнительные параметры безопасности».',
          'В качестве логина укажите полный адрес: <code>name@outlook.com</code>, <code>@hotmail.com</code> или <code>@live.ru</code>.',
          'Если двухшаговая проверка выключена, подойдёт обычный пароль — но включить её всё равно стоит.'],
        warns: [['<b>Папка «Нежелательная почта»</b> у Microsoft называется <code>Junk</code>, а не <code>Spam</code> — при ручном маппинге это частая ошибка.', 1],
          ['<b>Кириллические имена папок</b> кодируются в modified UTF-7. Мы декодируем их автоматически, но в чужих логах вы увидите <code>&amp;BB0EQgQ-</code> — это норма.', 1],
          ['<b>Старые Hotmail-ящики</b> иногда требуют однократного входа через веб-интерфейс, прежде чем IMAP начнёт отвечать.', 1]],
        cmd: 'imapsync \\\n  --host1 outlook.office365.com --port1 993 --ssl1 \\\n  --user1 anna@outlook.com --passfile1 /run/secrets/p1 \\\n  --host2 imap.new.com --port2 993 --ssl2 --user2 anna@new.com \\\n  --regextrans2 "s/^Junk$/Спам/" --automap',
      },
      yandex: {
        n: 'Яндекс.Почта',
        intro: 'Яндекс требует два отдельных действия: включить IMAP в почте и создать пароль приложения в Яндекс ID. Пропуск любого из них даёт одинаковую ошибку «AUTHENTICATIONFAILED», из-за чего люди часами проверяют не тот пароль.',
        conn: [['Сервер', 'imap.yandex.ru'], ['Порт', '993 · SSL/TLS'], ['Логин', 'логин без домена'], ['Пароль', 'пароль приложения']],
        steps: ['Почта → Настройки → «Почтовые программы» → включить «С сервера imap.yandex.ru по протоколу IMAP».',
          'Яндекс ID → Безопасность → «Пароли приложений» → создать пароль для типа «Почта».',
          'Для домена на Яндекс 360 логин — полный адрес; для обычного ящика достаточно логина без <code>@yandex.ru</code>.',
          'Проверьте, что в аккаунте не включён «Запрет доступа сторонним приложениям».'],
        warns: [['<b>Ограничение скорости</b> — Яндекс закрывает соединение при слишком частых запросах. Один поток и небольшие паузы работают стабильнее, чем пять потоков.', 1],
          ['<b>Папка «Удалённые»</b> очищается по расписанию сервера — переносить её обычно бессмысленно.', 1],
          ['<b>Яндекс 360 для бизнеса</b> — администратор может запретить IMAP на уровне организации; проверяйте до начала переноса.', 1]],
        cmd: 'imapsync \\\n  --host1 imap.yandex.ru --port1 993 --ssl1 --user1 anna \\\n  --passfile1 /run/secrets/p1 \\\n  --host2 imap.gmail.com --port2 993 --ssl2 --user2 anna@gmail.com \\\n  --passfile2 /run/secrets/p2 --automap --skipcrossduplicates',
      },
      icloud: {
        n: 'iCloud Mail',
        intro: 'У Apple пароль приложения обязателен всегда — обычный пароль Apple ID по IMAP не примут ни при каких настройках. Логин здесь тоже нестандартный: только часть до собаки.',
        conn: [['Сервер', 'imap.mail.me.com'], ['Порт', '993 · SSL/TLS'], ['Логин', 'часть до @'], ['Пароль', 'app-specific password']],
        steps: ['На appleid.apple.com включите двухфакторную аутентификацию, если она ещё не включена.',
          'Раздел «Безопасность» → «Пароли для приложений» → создать и скопировать пароль вида <code>abcd-efgh-ijkl-mnop</code>.',
          'В логин впишите только имя пользователя: для <code>anna@icloud.com</code> это <code>anna</code>.',
          'Дефисы в пароле сохраняйте — Apple их учитывает.'],
        warns: [['<b>Псевдонимы (aliases)</b> не имеют собственных ящиков: вся почта лежит в основном аккаунте.', 1],
          ['<b>Лимит одновременных подключений</b> низкий — параллельные переносы нескольких папок Apple рвёт.', 1],
          ['<b>@mac.com и @me.com</b> работают через тот же хост, менять ничего не нужно.', 1]],
        cmd: 'imapsync \\\n  --host1 imap.mail.me.com --port1 993 --ssl1 --user1 anna \\\n  --passfile1 /run/secrets/p1 \\\n  --host2 imap.new.com --port2 993 --ssl2 --user2 anna@new.com \\\n  --passfile2 /run/secrets/p2 --automap --maxbytespersecond 900000',
      },
      zoho: {
        n: 'Zoho Mail',
        intro: 'Частый выбор небольших компаний, уходящих с бесплатного Google Workspace. Главная особенность — региональные датацентры: неправильный хост даёт ошибку авторизации, а не ошибку соединения.',
        conn: [['Сервер', 'imap.zoho.com / .eu'], ['Порт', '993 · SSL/TLS'], ['Логин', 'полный адрес'], ['Пароль', 'app password']],
        steps: ['Zoho Mail → Settings → Mail Accounts → включить IMAP Access.',
          'Accounts → Security → App Passwords → создать пароль для MoveMailbox.',
          'Выберите правильный регион: <code>imap.zoho.com</code> (US), <code>imap.zoho.eu</code> (EU), <code>imap.zoho.in</code> (IN).',
          'Для бесплатного тарифа IMAP может быть недоступен — проверьте план до начала.'],
        warns: [['<b>Регион</b> — ящик, созданный в EU-датацентре, не отвечает на US-хосте, и наоборот. Ошибка выглядит как неверный пароль.', 1],
          ['<b>Бесплатный план</b> исторически ограничивает IMAP/POP. Если авторизация проходит, а папки пустые — дело в плане.', 1],
          ['<b>Zoho-специфичные папки</b> вроде <code>Templates</code> переносить не нужно.', 1]],
        cmd: 'imapsync \\\n  --host1 imap.zoho.eu --port1 993 --ssl1 --user1 anna@company.com \\\n  --passfile1 /run/secrets/p1 \\\n  --host2 outlook.office365.com --port2 993 --ssl2 \\\n  --user2 anna@company.com --oauthaccesstoken2 /run/secrets/tok \\\n  --office2 --automap',
      },
      cpanel: {
        n: 'cPanel / Dovecot / свой сервер',
        intro: 'Классический переезд с хостинга на хостинг. Технически самый простой случай — вы контролируете обе стороны, — но чаще всего ломается на сертификате: у shared-хостинга он выписан на имя сервера, а не на ваш домен.',
        conn: [['Сервер', 'mail.domain.tld'], ['Порт', '993 · SSL/TLS'], ['Логин', 'полный адрес'], ['Пароль', 'пароль ящика']],
        steps: ['Возьмите настройки в cPanel → Email Accounts → Connect Devices → секция «Secure SSL/TLS Settings».',
          'Логин почти всегда полный адрес: <code>anna@domain.tld</code>, а не <code>anna</code>.',
          'Если <code>mail.domain.tld</code> уже указывает на новый сервер, подключайтесь к старому по IP-адресу — поле хоста это принимает.',
          'При самоподписанном сертификате включите в расширенных настройках приём непроверенного сертификата.',
          'На своём Dovecot переносить лучше при остановленном доступе пользователей — иначе новые письма падают в оба ящика.'],
        warns: [['<b>Разделитель папок</b> — Dovecot использует <code>/</code>, старые Courier-серверы <code>.</code>. Из-за этого <code>INBOX.Sent</code> превращается в отдельную папку вместо вложенной.', 1],
          ['<b>Квота на назначении</b> — 12 ГБ не влезут в тариф на 5 ГБ. Проверьте квоту до запуска, иначе перенос встанет на середине.', 1],
          ['<b>Смена DNS</b> — переносите почту до переключения MX, а после переключения догоняйте вторым проходом: повторный запуск скопирует только новое.', 1],
          ['<b>Автоответы и фильтры</b> (Sieve) через IMAP не переносятся — их придётся перенести отдельно.', 1]],
        cmd: 'imapsync \\\n  --host1 203.0.113.10 --port1 993 --ssl1 --user1 anna@domain.tld \\\n  --passfile1 /run/secrets/p1 --sslargs1 SSL_verify_mode=0 \\\n  --host2 mail.newhost.tld --port2 993 --ssl2 --user2 anna@domain.tld \\\n  --passfile2 /run/secrets/p2 \\\n  --automap --usecache --skipsize --addheader',
      },
    },
  },
  en: {
    stepsTitle: 'Step by step',
    warnsTitle: 'Gotchas',
    cmdCaption: 'The imapsync equivalent — what MoveMailbox puts together for you',
    pv: {
      gmail: {
        n: 'Gmail / Google Workspace',
        intro: 'The most common source, and the most common place a transfer trips over. Gmail has no folders — it has labels, so a single message shows up in several “folders” at once, and a naive transfer happily produces duplicates.',
        conn: [['Server', 'imap.gmail.com'], ['Port', '993 · SSL/TLS'], ['Username', 'full address'], ['Password', 'app password']],
        steps: ['Turn on two-step verification in your Google account — app passwords are not available without it.',
          'Open the App passwords page, create a password named MoveMailbox and copy the 16 characters.',
          'In Gmail: Settings → Forwarding and POP/IMAP → “Enable IMAP” → Save.',
          'Paste the app password into the password field with no spaces. Your normal account password will not work.',
          'On Google Workspace, check that the admin has not disabled IMAP for the organisation.'],
        warns: [['<b>The All Mail label</b> — <code>[Gmail]/All Mail</code> holds a copy of every message. Leave it in and the volume doubles while duplicates land in the destination.', 1],
          ['<b>Volume cap</b> — Gmail serves roughly 2,500 MB per mailbox per day over IMAP. A large archive takes several days; that is normal, not a fault.', 1],
          ['<b>Trash and Spam</b> are usually not worth moving: untick <code>[Gmail]/Trash</code> and <code>[Gmail]/Spam</code>.', 1],
          ['<b>Temporary block</b> — push too hard and Google suspends IMAP for a few hours. We keep a single stream and pause between folders.', 1]],
        cmd: 'imapsync \\\n  --host1 imap.gmail.com --port1 993 --ssl1 \\\n  --user1 anna@old.com --passfile1 /run/secrets/p1 \\\n  --host2 imap.new.com --port2 993 --ssl2 \\\n  --user2 anna@new.com --passfile2 /run/secrets/p2 \\\n  --exclude "^\\[Gmail\\]/All Mail$" --exclude "^\\[Gmail\\]/Spam$" \\\n  --automap --dry',
      },
      m365: {
        n: 'Microsoft 365 / Exchange Online',
        intro: 'The route with the most money riding on it and the most demands. Microsoft switched off basic authentication for Exchange Online, so a plain username and password no longer gets through on most tenants — you need OAuth 2.0 (XOAUTH2).',
        conn: [['Server', 'outlook.office365.com'], ['Port', '993 · SSL/TLS'], ['Username', 'user UPN'], ['Authentication', 'OAuth 2.0 / XOAUTH2']],
        steps: ['Check that IMAP is enabled for the user: Exchange admin center → Recipients → Mailboxes → Manage email apps.',
          'If basic auth is off (it is by default), sign in with OAuth: MoveMailbox asks for access and gets a token — no password to type.',
          'On a tenant where OAuth has not been approved yet, an admin grants consent once to an app with the <code>IMAP.AccessAsUser.All</code> permission.',
          'For a single mailbox with MFA the alternative is an app password, but it is not available on every tenant and Microsoft is phasing it out.',
          'Mind the connection limit: 20 concurrent IMAP sessions per mailbox, beyond that the server starts dropping connections.'],
        warns: [['<b>Throttling</b> — Exchange Online slows writes down under load. On large mailboxes budget more time rather than more parallelism.', 1],
          ['<b>Special folders</b> — Archive, Conversation History and Notes move as ordinary IMAP folders, but their contents may look different in Outlook.', 1],
          ['<b>Message size</b> — 35 MB inbound by default. Messages with larger attachments are skipped and listed in the report.', 1],
          ['<b>In-Place Archive</b> mailboxes are not visible over IMAP at all — separate storage, different tool.', 1]],
        cmd: 'imapsync \\\n  --host1 imap.old.com --port1 993 --ssl1 --user1 anna@old.com \\\n  --host2 outlook.office365.com --port2 993 --ssl2 \\\n  --user2 anna@company.com \\\n  --oauthaccesstoken2 /run/secrets/o365.token \\\n  --office2 --automap --useuid',
      },
      outlook: {
        n: 'Outlook.com / Hotmail / Live',
        intro: 'Personal Microsoft mailboxes. Same host as corporate 365, but app passwords still work here — with two-step verification turned on, that is the simplest way in.',
        conn: [['Server', 'outlook.office365.com'], ['Port', '993 · SSL/TLS'], ['Username', 'full address'], ['Password', 'app password']],
        steps: ['Turn on two-step verification in the security settings of your Microsoft account.',
          'Create an app password under “Additional security options”.',
          'Use the full address as the username: <code>name@outlook.com</code>, <code>@hotmail.com</code> or <code>@live.ru</code>.',
          'With two-step verification off the ordinary password works — but turning it on is worth it anyway.'],
        warns: [['<b>The junk folder</b> is called <code>Junk</code> at Microsoft, not <code>Spam</code> — a frequent slip when folders are mapped by hand.', 1],
          ['<b>Non-Latin folder names</b> are encoded in modified UTF-7. We decode them automatically, but in other tools’ logs you will see <code>&amp;BB0EQgQ-</code> — that is expected.', 1],
          ['<b>Old Hotmail mailboxes</b> sometimes need one sign-in through the web interface before IMAP starts answering.', 1]],
        cmd: 'imapsync \\\n  --host1 outlook.office365.com --port1 993 --ssl1 \\\n  --user1 anna@outlook.com --passfile1 /run/secrets/p1 \\\n  --host2 imap.new.com --port2 993 --ssl2 --user2 anna@new.com \\\n  --regextrans2 "s/^Junk$/Spam/" --automap',
      },
      yandex: {
        n: 'Yandex Mail',
        intro: 'Yandex needs two separate steps: enable IMAP in the mail settings and create an app password in Yandex ID. Miss either one and you get the same AUTHENTICATIONFAILED error, which is why people spend hours checking the wrong password.',
        conn: [['Server', 'imap.yandex.ru'], ['Port', '993 · SSL/TLS'], ['Username', 'login without the domain'], ['Password', 'app password']],
        steps: ['Mail → Settings → “Email clients” → enable “From the imap.yandex.ru server over IMAP”.',
          'Yandex ID → Security → “App passwords” → create a password for the “Mail” type.',
          'On a Yandex 360 domain the username is the full address; for a regular mailbox the login without <code>@yandex.ru</code> is enough.',
          'Check that “Block access for third-party apps” is not switched on for the account.'],
        warns: [['<b>Rate limiting</b> — Yandex closes the connection when requests come in too fast. One stream with short pauses is steadier than five streams.', 1],
          ['<b>The Deleted folder</b> is purged on the server’s own schedule — usually pointless to move.', 1],
          ['<b>Yandex 360 for Business</b> — an admin can block IMAP for the whole organisation; check that before you start the transfer.', 1]],
        cmd: 'imapsync \\\n  --host1 imap.yandex.ru --port1 993 --ssl1 --user1 anna \\\n  --passfile1 /run/secrets/p1 \\\n  --host2 imap.gmail.com --port2 993 --ssl2 --user2 anna@gmail.com \\\n  --passfile2 /run/secrets/p2 --automap --skipcrossduplicates',
      },
      icloud: {
        n: 'iCloud Mail',
        intro: 'Apple always requires an app password — a normal Apple ID password will never be accepted over IMAP, whatever you configure. The username is unusual too: only the part before the @.',
        conn: [['Server', 'imap.mail.me.com'], ['Port', '993 · SSL/TLS'], ['Username', 'the part before @'], ['Password', 'app-specific password']],
        steps: ['On appleid.apple.com turn on two-factor authentication if it is not on already.',
          '“Security” → “App-Specific Passwords” → create one and copy a password shaped like <code>abcd-efgh-ijkl-mnop</code>.',
          'Enter only the user name as the login: for <code>anna@icloud.com</code> that is <code>anna</code>.',
          'Keep the hyphens in the password — Apple counts them.'],
        warns: [['<b>Aliases</b> have no mailbox of their own: all the mail sits in the main account.', 1],
          ['<b>The cap on simultaneous connections</b> is low — Apple drops parallel transfers of several folders.', 1],
          ['<b>@mac.com and @me.com</b> run through the same host, nothing to change.', 1]],
        cmd: 'imapsync \\\n  --host1 imap.mail.me.com --port1 993 --ssl1 --user1 anna \\\n  --passfile1 /run/secrets/p1 \\\n  --host2 imap.new.com --port2 993 --ssl2 --user2 anna@new.com \\\n  --passfile2 /run/secrets/p2 --automap --maxbytespersecond 900000',
      },
      zoho: {
        n: 'Zoho Mail',
        intro: 'A common pick for small companies leaving the free Google Workspace tier. The thing to watch is the regional data centres: the wrong host gives you an authentication error, not a connection error.',
        conn: [['Server', 'imap.zoho.com / .eu'], ['Port', '993 · SSL/TLS'], ['Username', 'full address'], ['Password', 'app password']],
        steps: ['Zoho Mail → Settings → Mail Accounts → enable IMAP Access.',
          'Accounts → Security → App Passwords → create a password for MoveMailbox.',
          'Pick the right region: <code>imap.zoho.com</code> (US), <code>imap.zoho.eu</code> (EU), <code>imap.zoho.in</code> (IN).',
          'On the free plan IMAP may be unavailable — check the plan before you start.'],
        warns: [['<b>Region</b> — a mailbox created in the EU data centre will not answer on the US host, and the other way round. The error looks like a wrong password.', 1],
          ['<b>The free plan</b> has historically restricted IMAP/POP. If authentication succeeds but the folders come back empty, the plan is the reason.', 1],
          ['<b>Zoho-specific folders</b> such as <code>Templates</code> do not need to be moved.', 1]],
        cmd: 'imapsync \\\n  --host1 imap.zoho.eu --port1 993 --ssl1 --user1 anna@company.com \\\n  --passfile1 /run/secrets/p1 \\\n  --host2 outlook.office365.com --port2 993 --ssl2 \\\n  --user2 anna@company.com --oauthaccesstoken2 /run/secrets/tok \\\n  --office2 --automap',
      },
      cpanel: {
        n: 'cPanel / Dovecot / your own server',
        intro: 'The classic host-to-host move. Technically the easiest case — you control both ends — but it usually breaks on the certificate: on shared hosting it is issued for the server name, not for your domain.',
        conn: [['Server', 'mail.domain.tld'], ['Port', '993 · SSL/TLS'], ['Username', 'full address'], ['Password', 'mailbox password']],
        steps: ['Take the settings from cPanel → Email Accounts → Connect Devices → the “Secure SSL/TLS Settings” block.',
          'The username is almost always the full address: <code>anna@domain.tld</code>, not <code>anna</code>.',
          'If <code>mail.domain.tld</code> already points at the new server, connect to the old one by IP address — the host field accepts that.',
          'With a self-signed certificate, allow an unverified certificate in the advanced settings.',
          'On your own Dovecot it is better to run the transfer with user access stopped — otherwise new mail lands in both mailboxes.'],
        warns: [['<b>Folder separator</b> — Dovecot uses <code>/</code>, older Courier servers use <code>.</code>. That is why <code>INBOX.Sent</code> ends up as a separate folder instead of a nested one.', 1],
          ['<b>Quota on the destination</b> — 12 GB will not fit into a 5 GB plan. Check the quota before you start, or the transfer stalls halfway.', 1],
          ['<b>DNS switch</b> — move the mail before you switch MX, then catch up with a second pass afterwards: a re-run copies only what is new.', 1],
          ['<b>Autoresponders and filters</b> (Sieve) do not travel over IMAP — you will have to move them separately.', 1]],
        cmd: 'imapsync \\\n  --host1 203.0.113.10 --port1 993 --ssl1 --user1 anna@domain.tld \\\n  --passfile1 /run/secrets/p1 --sslargs1 SSL_verify_mode=0 \\\n  --host2 mail.newhost.tld --port2 993 --ssl2 --user2 anna@domain.tld \\\n  --passfile2 /run/secrets/p2 \\\n  --automap --usecache --skipsize --addheader',
      },
    },
  },
  uk: {
    stepsTitle: 'Покроково',
    warnsTitle: 'Підводні камені',
    cmdCaption: 'Еквівалент в imapsync — те, що MoveMailbox збере за вас',
    pv: {
      gmail: {
        n: 'Gmail / Google Workspace',
        intro: 'Найчастіше джерело і найчастіше місце, де перенесення спотикається. Gmail не зберігає папки — він зберігає мітки, тому один лист видно одразу в кількох «папках», і наївне перенесення легко створює дублікати.',
        conn: [['Сервер', 'imap.gmail.com'], ['Порт', '993 · SSL/TLS'], ['Логін', 'повна адреса'], ['Пароль', 'пароль застосунку']],
        steps: ['В обліковому записі Google увімкніть двоетапну автентифікацію — без неї паролі застосунків недоступні.',
          'Відкрийте розділ «Паролі застосунків», створіть пароль з іменем MoveMailbox і скопіюйте 16 символів.',
          'У Gmail: Налаштування → Пересилання і POP/IMAP → «Увімкнути IMAP» → Зберегти.',
          'У поле пароля вставте пароль застосунку без пробілів. Звичайний пароль облікового запису не спрацює.',
          'Для Google Workspace переконайтеся, що адміністратор не вимкнув IMAP для організації.'],
        warns: [['<b>Мітка «Вся пошта»</b> — <code>[Gmail]/All Mail</code> містить копії всіх листів. Якщо її не виключити, обсяг подвоюється, а в призначення приїжджають дублі.', 1],
          ['<b>Ліміт на обсяг</b> — Gmail віддає приблизно 2 500 МБ на добу на скриньку через IMAP. Великий архів їде кілька днів, це нормально, а не поломка.', 1],
          ['<b>Кошик і Спам</b> зазвичай переносити не потрібно: зніміть галочки на <code>[Gmail]/Trash</code> та <code>[Gmail]/Spam</code>.', 1],
          ['<b>Призупинення</b> — за надто агресивної швидкості Google тимчасово блокує IMAP на кілька годин. Ми тримаємо один потік і паузи між папками.', 1]],
        cmd: 'imapsync \\\n  --host1 imap.gmail.com --port1 993 --ssl1 \\\n  --user1 anna@old.com --passfile1 /run/secrets/p1 \\\n  --host2 imap.new.com --port2 993 --ssl2 \\\n  --user2 anna@new.com --passfile2 /run/secrets/p2 \\\n  --exclude "^\\[Gmail\\]/All Mail$" --exclude "^\\[Gmail\\]/Spam$" \\\n  --automap --dry',
      },
      m365: {
        n: 'Microsoft 365 / Exchange Online',
        intro: 'Найгрошовитіший маршрут і найвибагливіший. Microsoft вимкнув basic authentication для Exchange Online, тому звичайна пара «логін + пароль» на більшості тенантів уже не проходить — потрібен OAuth 2.0 (XOAUTH2).',
        conn: [['Сервер', 'outlook.office365.com'], ['Порт', '993 · SSL/TLS'], ['Логін', 'UPN користувача'], ['Автентифікація', 'OAuth 2.0 / XOAUTH2']],
        steps: ['Переконайтеся, що в користувача увімкнено IMAP: Exchange admin center → Одержувачі → Поштові скриньки → Керування поштовими застосунками.',
          'Якщо basic auth вимкнено (за замовчуванням саме так) — авторизуйтеся через OAuth: MoveMailbox запитає доступ і отримає токен, пароль вводити не потрібно.',
          'Для тенанта, де OAuth ще не погоджено, адміністратор один раз надає згоду застосунку з правом <code>IMAP.AccessAsUser.All</code>.',
          'Альтернатива для однієї скриньки з MFA — пароль застосунку, але він доступний не в усіх тенантах, і Microsoft його згортає.',
          'Перевірте ліміт підключень: 20 одночасних IMAP-сесій на скриньку, інакше сервер почне рвати з’єднання.'],
        warns: [['<b>Throttling</b> — Exchange Online ріже швидкість під час інтенсивного запису. На великих скриньках закладайте час, а не збільшуйте паралелізм.', 1],
          ['<b>Спецпапки</b> — Archive, Conversation History і Notes переносяться як звичайні IMAP-папки, але їхній вміст в Outlook може виглядати інакше.', 1],
          ['<b>Розмір листа</b> — за замовчуванням 35 МБ на вхідний. Листи з великими вкладеннями буде пропущено, і вони потраплять у звіт.', 1],
          ['<b>Особисті архіви</b> (In-Place Archive) через IMAP не видно взагалі — це окреме сховище, потрібен інший інструмент.', 1]],
        cmd: 'imapsync \\\n  --host1 imap.old.com --port1 993 --ssl1 --user1 anna@old.com \\\n  --host2 outlook.office365.com --port2 993 --ssl2 \\\n  --user2 anna@company.com \\\n  --oauthaccesstoken2 /run/secrets/o365.token \\\n  --office2 --automap --useuid',
      },
      outlook: {
        n: 'Outlook.com / Hotmail / Live',
        intro: 'Особисті скриньки Microsoft. Хост той самий, що й у корпоративного 365, але пароль застосунку тут ще підтримується — за увімкненої двоетапної перевірки це найпростіший шлях.',
        conn: [['Сервер', 'outlook.office365.com'], ['Порт', '993 · SSL/TLS'], ['Логін', 'повна адреса'], ['Пароль', 'пароль застосунку']],
        steps: ['Увімкніть двоетапну перевірку в налаштуваннях безпеки облікового запису Microsoft.',
          'Створіть пароль застосунку в розділі «Додаткові параметри безпеки».',
          'Як логін укажіть повну адресу: <code>name@outlook.com</code>, <code>@hotmail.com</code> або <code>@live.ru</code>.',
          'Якщо двоетапну перевірку вимкнено, підійде звичайний пароль — але увімкнути її все одно варто.'],
        warns: [['<b>Папка «Небажана пошта»</b> у Microsoft називається <code>Junk</code>, а не <code>Spam</code> — під час ручного маппінгу це часта помилка.', 1],
          ['<b>Кириличні імена папок</b> кодуються в modified UTF-7. Ми декодуємо їх автоматично, але в чужих журналах ви побачите <code>&amp;BB0EQgQ-</code> — це норма.', 1],
          ['<b>Старі Hotmail-скриньки</b> іноді вимагають одноразового входу через вебінтерфейс, перш ніж IMAP почне відповідати.', 1]],
        cmd: 'imapsync \\\n  --host1 outlook.office365.com --port1 993 --ssl1 \\\n  --user1 anna@outlook.com --passfile1 /run/secrets/p1 \\\n  --host2 imap.new.com --port2 993 --ssl2 --user2 anna@new.com \\\n  --regextrans2 "s/^Junk$/Спам/" --automap',
      },
      yandex: {
        n: 'Яндекс.Пошта',
        intro: 'Яндекс вимагає дві окремі дії: увімкнути IMAP у пошті та створити пароль застосунку в Яндекс ID. Пропуск будь-якої з них дає однакову помилку «AUTHENTICATIONFAILED», через що люди годинами перевіряють не той пароль.',
        conn: [['Сервер', 'imap.yandex.ru'], ['Порт', '993 · SSL/TLS'], ['Логін', 'логін без домену'], ['Пароль', 'пароль застосунку']],
        steps: ['Пошта → Налаштування → «Поштові програми» → увімкнути «З сервера imap.yandex.ru за протоколом IMAP».',
          'Яндекс ID → Безпека → «Паролі застосунків» → створити пароль для типу «Пошта».',
          'Для домену на Яндекс 360 логін — повна адреса; для звичайної скриньки достатньо логіна без <code>@yandex.ru</code>.',
          'Перевірте, що в обліковому записі не ввімкнено «Заборону доступу стороннім застосункам».'],
        warns: [['<b>Обмеження швидкості</b> — Яндекс закриває з’єднання за надто частих запитів. Один потік і невеликі паузи працюють стабільніше, ніж п’ять потоків.', 1],
          ['<b>Папка «Видалені»</b> очищується за розкладом сервера — переносити її зазвичай немає сенсу.', 1],
          ['<b>Яндекс 360 для бізнесу</b> — адміністратор може заборонити IMAP на рівні організації; перевіряйте до початку перенесення.', 1]],
        cmd: 'imapsync \\\n  --host1 imap.yandex.ru --port1 993 --ssl1 --user1 anna \\\n  --passfile1 /run/secrets/p1 \\\n  --host2 imap.gmail.com --port2 993 --ssl2 --user2 anna@gmail.com \\\n  --passfile2 /run/secrets/p2 --automap --skipcrossduplicates',
      },
      icloud: {
        n: 'iCloud Mail',
        intro: 'В Apple пароль застосунку обов’язковий завжди — звичайний пароль Apple ID по IMAP не приймуть за жодних налаштувань. Логін тут теж нестандартний: лише частина до равлика.',
        conn: [['Сервер', 'imap.mail.me.com'], ['Порт', '993 · SSL/TLS'], ['Логін', 'частина до @'], ['Пароль', 'app-specific password']],
        steps: ['На appleid.apple.com увімкніть двофакторну автентифікацію, якщо її ще не ввімкнено.',
          'Розділ «Безпека» → «Паролі для програм» → створити та скопіювати пароль вигляду <code>abcd-efgh-ijkl-mnop</code>.',
          'У логін впишіть лише ім’я користувача: для <code>anna@icloud.com</code> це <code>anna</code>.',
          'Дефіси в паролі зберігайте — Apple їх враховує.'],
        warns: [['<b>Псевдоніми (aliases)</b> не мають власних скриньок: уся пошта лежить в основному обліковому записі.', 1],
          ['<b>Ліміт одночасних підключень</b> низький — паралельне перенесення кількох папок Apple рве.', 1],
          ['<b>@mac.com і @me.com</b> працюють через той самий хост, міняти нічого не потрібно.', 1]],
        cmd: 'imapsync \\\n  --host1 imap.mail.me.com --port1 993 --ssl1 --user1 anna \\\n  --passfile1 /run/secrets/p1 \\\n  --host2 imap.new.com --port2 993 --ssl2 --user2 anna@new.com \\\n  --passfile2 /run/secrets/p2 --automap --maxbytespersecond 900000',
      },
      zoho: {
        n: 'Zoho Mail',
        intro: 'Частий вибір невеликих компаній, що йдуть із безкоштовного Google Workspace. Головна особливість — регіональні дата-центри: неправильний хост дає помилку авторизації, а не помилку з’єднання.',
        conn: [['Сервер', 'imap.zoho.com / .eu'], ['Порт', '993 · SSL/TLS'], ['Логін', 'повна адреса'], ['Пароль', 'app password']],
        steps: ['Zoho Mail → Settings → Mail Accounts → увімкнути IMAP Access.',
          'Accounts → Security → App Passwords → створити пароль для MoveMailbox.',
          'Оберіть правильний регіон: <code>imap.zoho.com</code> (US), <code>imap.zoho.eu</code> (EU), <code>imap.zoho.in</code> (IN).',
          'Для безкоштовного тарифу IMAP може бути недоступний — перевірте план до початку.'],
        warns: [['<b>Регіон</b> — скринька, створена в EU-дата-центрі, не відповідає на US-хості, і навпаки. Помилка виглядає як неправильний пароль.', 1],
          ['<b>Безкоштовний план</b> історично обмежує IMAP/POP. Якщо авторизація проходить, а папки порожні — річ у плані.', 1],
          ['<b>Zoho-специфічні папки</b> на кшталт <code>Templates</code> переносити не потрібно.', 1]],
        cmd: 'imapsync \\\n  --host1 imap.zoho.eu --port1 993 --ssl1 --user1 anna@company.com \\\n  --passfile1 /run/secrets/p1 \\\n  --host2 outlook.office365.com --port2 993 --ssl2 \\\n  --user2 anna@company.com --oauthaccesstoken2 /run/secrets/tok \\\n  --office2 --automap',
      },
      cpanel: {
        n: 'cPanel / Dovecot / власний сервер',
        intro: 'Класичний переїзд з хостингу на хостинг. Технічно найпростіший випадок — ви контролюєте обидві сторони, — але найчастіше ламається на сертифікаті: у shared-хостингу він виписаний на ім’я сервера, а не на ваш домен.',
        conn: [['Сервер', 'mail.domain.tld'], ['Порт', '993 · SSL/TLS'], ['Логін', 'повна адреса'], ['Пароль', 'пароль скриньки']],
        steps: ['Візьміть налаштування в cPanel → Email Accounts → Connect Devices → секція «Secure SSL/TLS Settings».',
          'Логін майже завжди повна адреса: <code>anna@domain.tld</code>, а не <code>anna</code>.',
          'Якщо <code>mail.domain.tld</code> уже вказує на новий сервер, підключайтеся до старого за IP-адресою — поле хоста це приймає.',
          'За самопідписаного сертифіката увімкніть у розширених налаштуваннях прийом неперевіреного сертифіката.',
          'На власному Dovecot переносити краще із зупиненим доступом користувачів — інакше нові листи падають в обидві скриньки.'],
        warns: [['<b>Роздільник папок</b> — Dovecot використовує <code>/</code>, старі Courier-сервери <code>.</code>. Через це <code>INBOX.Sent</code> перетворюється на окрему папку замість вкладеної.', 1],
          ['<b>Квота на призначенні</b> — 12 ГБ не влізуть у тариф на 5 ГБ. Перевірте квоту до запуску, інакше перенесення стане на середині.', 1],
          ['<b>Зміна DNS</b> — переносьте пошту до перемикання MX, а після перемикання наздоганяйте другим проходом: повторний запуск скопіює лише нове.', 1],
          ['<b>Автовідповіді та фільтри</b> (Sieve) через IMAP не переносяться — їх доведеться перенести окремо.', 1]],
        cmd: 'imapsync \\\n  --host1 203.0.113.10 --port1 993 --ssl1 --user1 anna@domain.tld \\\n  --passfile1 /run/secrets/p1 --sslargs1 SSL_verify_mode=0 \\\n  --host2 mail.newhost.tld --port2 993 --ssl2 --user2 anna@domain.tld \\\n  --passfile2 /run/secrets/p2 \\\n  --automap --usecache --skipsize --addheader',
      },
    },
  },
} as const;
