/** Копия секции «Популярные направления». Один файл на секцию — три языка рядом. */
export const popularRoutes = {
  ru: {
    eyebrow: 'Популярные направления',
    h2a: 'Понятные инструкции ',
    h2b: 'для частых переездов.',
    lede: 'Выберите готовый маршрут — «перенести из … в …» — или подключите любые два совместимых IMAP-сервера вручную.',
    guide: 'Гайд',
    manual: 'Вручную',
    any: 'Любой',
    yandex: 'Яндекс',
    oldHost: 'Старый хостинг',
    newHost: 'Новый хостинг',
    aria1: 'Перенести почту из Gmail в Outlook',
    aria2: 'Перенести почту из Outlook в Gmail',
    aria3: 'Перенести почту из Yahoo Mail в Gmail',
    aria4: 'Перенести почту из iCloud Mail в Gmail',
    aria5: 'Перенести почту из cPanel в Microsoft 365',
    aria6: 'Перенести почту из Яндекс в Zoho',
    aria7: 'Перенести почту из Старый хостинг в Новый хостинг',
  },
  en: {
    eyebrow: 'Popular routes',
    h2a: 'Clear guides ',
    h2b: 'for the moves people make.',
    lede: 'Pick a ready-made route — “move from … to …” — or connect any two compatible IMAP servers by hand.',
    guide: 'Guide',
    manual: 'Manual',
    any: 'Any',
    yandex: 'Yandex',
    oldHost: 'Old host',
    newHost: 'New host',
    aria1: 'Move mail from Gmail to Outlook',
    aria2: 'Move mail from Outlook to Gmail',
    aria3: 'Move mail from Yahoo Mail to Gmail',
    aria4: 'Move mail from iCloud Mail to Gmail',
    aria5: 'Move mail from cPanel to Microsoft 365',
    aria6: 'Move mail from Yandex to Zoho',
    aria7: 'Move mail from an old host to a new host',
  },
  uk: {
    eyebrow: 'Популярні напрямки',
    h2a: 'Зрозумілі інструкції ',
    h2b: 'для частих переїздів.',
    lede: 'Оберіть готовий маршрут — «перенести з … до …» — або підключіть будь-які два сумісні IMAP-сервери вручну.',
    guide: 'Інструкція',
    manual: 'Вручну',
    any: 'Будь-який',
    yandex: 'Яндекс',
    oldHost: 'Старий хостинг',
    newHost: 'Новий хостинг',
    aria1: 'Перенести пошту з Gmail до Outlook',
    aria2: 'Перенести пошту з Outlook до Gmail',
    aria3: 'Перенести пошту з Yahoo Mail до Gmail',
    aria4: 'Перенести пошту з iCloud Mail до Gmail',
    aria5: 'Перенести пошту з cPanel до Microsoft 365',
    aria6: 'Перенести пошту з Яндекса до Zoho',
    aria7: 'Перенести пошту зі старого хостингу на новий',
  },
} as const;
