/** Копия секции «Тарифы». Один файл на секцию — три языка рядом.
 * Суммы одинаковы во всех языках — меняются только слова вокруг. */
export const pricing = {
  ru: {
    plannedNotice: 'Планируемые тарифы. Продажи и онлайн-перенос ещё не открыты; цены могут измениться до запуска.',
    eyebrow: 'Простая цена за один полный ящик',
    h2a: 'Сначала узнаём объём. ',
    h2b: 'Потом запускаем.',
    lede: 'Один платёж за ящик, не подписка. Объём измеряется до запуска и бесплатно: если ящик укладывается в 5 ГБ, он переезжает целиком и даром.',
    free: {
      name: 'Free',
      tag: 'Для знакомства',
      amount: '$0',
      per: '',
      lim: 'до 5 ГБ',
      nt: 'Один полный ящик',
      ticks: ['Проверка двух подключений', 'Стандартная очередь', 'Отчёт о переносе'],
    },
    standard: {
      name: 'Standard',
      tag: 'Популярный',
      amount: '$5.90 ',
      per: '/ ящик',
      lim: 'до 25 ГБ',
      nt: 'Разовый платёж',
      ticks: ['Приоритет над Free', 'Повторный запуск', 'Email-уведомление'],
    },
    large: {
      name: 'Large',
      tag: 'Большой ящик',
      amount: '$11.90 ',
      per: '/ ящик',
      lim: 'до 100 ГБ',
      nt: 'Разовый платёж',
      ticks: ['Большие ящики', 'Увеличенное время worker', 'Расширенный отчёт'],
    },
    business: {
      name: 'Business',
      tag: 'B2B',
      amount: 'По запросу',
      per: '',
      lim: 'пакет ящиков',
      nt: 'Для IT-команд',
      ticks: ['CSV-пакеты', 'Общий отчёт', 'Приоритетная очередь'],
    },
  },
  en: {
    plannedNotice: 'Planned pricing. Sales and online transfer are not open yet; prices may change before launch.',
    eyebrow: 'One simple price per full mailbox',
    h2a: 'First we measure the size. ',
    h2b: 'Then we start.',
    lede: 'One payment per mailbox, not a subscription. The size check runs before the transfer and costs nothing: if the mailbox fits into 5 GB, the whole thing moves for free.',
    free: {
      name: 'Free',
      tag: 'To try it out',
      amount: '$0',
      per: '',
      lim: 'up to 5 GB',
      nt: 'One full mailbox',
      ticks: ['Both connections checked', 'Standard queue', 'Transfer report'],
    },
    standard: {
      name: 'Standard',
      tag: 'Most popular',
      amount: '$5.90 ',
      per: '/ mailbox',
      lim: 'up to 25 GB',
      nt: 'One-time payment',
      ticks: ['Priority over Free', 'Re-run included', 'Email notification'],
    },
    large: {
      name: 'Large',
      tag: 'Large mailbox',
      amount: '$11.90 ',
      per: '/ mailbox',
      lim: 'up to 100 GB',
      nt: 'One-time payment',
      ticks: ['Large mailboxes', 'Longer worker time', 'Extended report'],
    },
    business: {
      name: 'Business',
      tag: 'B2B',
      amount: 'On request',
      per: '',
      lim: 'batch of mailboxes',
      nt: 'For IT teams',
      ticks: ['CSV batches', 'Combined report', 'Priority queue'],
    },
  },
  uk: {
    plannedNotice: 'Заплановані тарифи. Продажі та онлайн-перенесення ще не відкриті; ціни можуть змінитися до запуску.',
    eyebrow: 'Проста ціна за одну повну скриньку',
    h2a: 'Спершу дізнаємося обсяг. ',
    h2b: 'Потім запускаємо.',
    lede: 'Один платіж за скриньку, не підписка. Обсяг вимірюється до запуску і безкоштовно: якщо скринька вкладається в 5 ГБ, вона переїжджає цілком і задарма.',
    free: {
      name: 'Free',
      tag: 'Для знайомства',
      amount: '$0',
      per: '',
      lim: 'до 5 ГБ',
      nt: 'Одна повна скринька',
      ticks: ['Перевірка двох підключень', 'Стандартна черга', 'Звіт про перенесення'],
    },
    standard: {
      name: 'Standard',
      tag: 'Популярний',
      amount: '$5.90 ',
      per: '/ скриньку',
      lim: 'до 25 ГБ',
      nt: 'Разовий платіж',
      ticks: ['Пріоритет над Free', 'Повторний запуск', 'Email-сповіщення'],
    },
    large: {
      name: 'Large',
      tag: 'Велика скринька',
      amount: '$11.90 ',
      per: '/ скриньку',
      lim: 'до 100 ГБ',
      nt: 'Разовий платіж',
      ticks: ['Великі скриньки', 'Збільшений час worker', 'Розширений звіт'],
    },
    business: {
      name: 'Business',
      tag: 'B2B',
      amount: 'На запит',
      per: '',
      lim: 'пакет скриньок',
      nt: 'Для IT-команд',
      ticks: ['CSV-пакети', 'Спільний звіт', 'Пріоритетна черга'],
    },
  },
} as const;
