/** Копия секции «Границы протокола». Один файл на секцию — три языка рядом. */
export const protocolLimits = {
  ru: {
    eyebrow: 'Границы протокола',
    h2a: 'Что переезжает вместе с почтой, ',
    h2b: 'а что придётся перенести руками.',
    lede: 'IMAP — протокол про письма и папки, и только про них. Всё остальное живёт вне его, и честнее сказать об этом до переноса, чем услышать вопрос после.',
    yesBadge: 'Переносится',
    yesNote: 'Полностью, байт в байт, без переупаковки',
    yes: [
      { b: 'Письма целиком', s: 'Исходный RFC 822 объект: заголовки, тело, все вложения' },
      { b: 'Даты получения', s: 'Порядок в ящике не сбивается, письма не становятся «сегодняшними»' },
      { b: 'Флаги', s: 'Прочитано, отвечено, помечено, черновик' },
      { b: 'Структура папок', s: 'Вложенность любой глубины, кириллические имена в UTF-7' },
      { b: 'Отправленные и черновики', s: 'Обычные IMAP-папки, переносятся наравне с входящими' },
    ],
    noBadge: 'Не переносится',
    noNote: 'Это не IMAP — данные лежат в других системах провайдера',
    no: [
      { b: 'Контакты и календари', s: 'Живут в CardDAV и CalDAV — выгружаются отдельно, в vCard и ICS' },
      { b: 'Фильтры и правила', s: 'Sieve или правила Outlook — пересоздаются в новом ящике вручную' },
      { b: 'Автоответчик и подписи', s: 'Настройки веб-интерфейса, к письмам отношения не имеют' },
      { b: 'Алиасы и пересылки', s: 'Конфигурация домена — переносится вместе с DNS и MX' },
      { b: 'In-Place Archive у Microsoft', s: 'Отдельное хранилище, по IMAP не видно вообще' },
    ],
    footLabel: 'Что с этим делать:',
    footText: 'контакты и календарь выгрузите из старого веб-интерфейса в vCard и ICS до отключения ящика — это пять минут, но только пока доступ ещё есть. Фильтры проще переписать заново: за годы их обычно накапливается больше, чем нужно.',
  },
  en: {
    eyebrow: 'Protocol boundaries',
    h2a: 'What moves with the mail, ',
    h2b: 'and what you have to move by hand.',
    lede: 'IMAP is a protocol about messages and folders, and only about those. Everything else lives outside it, and it is fairer to say so before the transfer than to field the question after.',
    yesBadge: 'Transfers',
    yesNote: 'In full, byte for byte, with no repacking',
    yes: [
      { b: 'Whole messages', s: 'The original RFC 822 object: headers, body, every attachment' },
      { b: 'Received dates', s: 'Mailbox order stays intact — nothing turns up dated today' },
      { b: 'Flags', s: 'Seen, answered, flagged, draft' },
      { b: 'Folder structure', s: 'Nesting of any depth, non-ASCII names in UTF-7' },
      { b: 'Sent and Drafts', s: 'Ordinary IMAP folders — they move like the inbox does' },
    ],
    noBadge: 'Does not transfer',
    noNote: 'This is not IMAP — the data sits in other systems at the provider',
    no: [
      { b: 'Contacts and calendars', s: 'They live in CardDAV and CalDAV — export them separately, as vCard and ICS' },
      { b: 'Filters and rules', s: 'Sieve or Outlook rules — recreate them by hand in the new mailbox' },
      { b: 'Auto-reply and signatures', s: 'Webmail settings, nothing to do with the messages themselves' },
      { b: 'Aliases and forwarding', s: 'Domain configuration — it moves along with DNS and MX' },
      { b: 'In-Place Archive at Microsoft', s: 'A separate store, not visible over IMAP at all' },
    ],
    footLabel: 'What to do about it:',
    footText: 'export contacts and the calendar from the old webmail to vCard and ICS before the mailbox is shut off — it takes five minutes, but only while you still have access. Filters are easier to write from scratch: over the years you usually collect more of them than you need.',
  },
  uk: {
    eyebrow: 'Межі протоколу',
    h2a: 'Що переїжджає разом із поштою, ',
    h2b: 'а що доведеться перенести руками.',
    lede: 'IMAP — протокол про листи й папки, і лише про них. Усе інше живе поза ним, і чесніше сказати про це до перенесення, ніж почути питання потім.',
    yesBadge: 'Переноситься',
    yesNote: 'Повністю, байт у байт, без перепакування',
    yes: [
      { b: 'Листи цілком', s: 'Вихідний RFC 822 об’єкт: заголовки, тіло, усі вкладення' },
      { b: 'Дати отримання', s: 'Порядок у скриньці не збивається, листи не стають «сьогоднішніми»' },
      { b: 'Прапорці', s: 'Прочитано, відповіджено, позначено, чернетка' },
      { b: 'Структура папок', s: 'Вкладеність будь-якої глибини, кириличні назви в UTF-7' },
      { b: 'Надіслані та чернетки', s: 'Звичайні IMAP-папки, переносяться нарівні з вхідними' },
    ],
    noBadge: 'Не переноситься',
    noNote: 'Це не IMAP — дані лежать в інших системах провайдера',
    no: [
      { b: 'Контакти й календарі', s: 'Живуть у CardDAV і CalDAV — вивантажуються окремо, у vCard та ICS' },
      { b: 'Фільтри та правила', s: 'Sieve або правила Outlook — створюються в новій скриньці вручну' },
      { b: 'Автовідповідач і підписи', s: 'Налаштування вебінтерфейсу, до листів стосунку не мають' },
      { b: 'Аліаси та пересилання', s: 'Конфігурація домену — переноситься разом із DNS і MX' },
      { b: 'In-Place Archive у Microsoft', s: 'Окреме сховище, по IMAP не видно взагалі' },
    ],
    footLabel: 'Що з цим робити:',
    footText: 'контакти та календар вивантажте зі старого вебінтерфейсу у vCard та ICS до вимкнення скриньки — це п’ять хвилин, але лише поки доступ ще є. Фільтри простіше переписати наново: за роки їх зазвичай накопичується більше, ніж потрібно.',
  },
} as const;
