/** Строки, которые подставляет императивный код рабочей области (lib/workspace.ts):
 * статусы, кнопки режимов, сообщения журнала и модалка строгого зеркала.
 * Разметка секции переведена отдельно — в workspace.ts. */
export const workspaceRuntime = {
  ru: {
    offlineStatus: 'Онлайн-перенос ещё не запущен — проверка недоступна',
    numberLocale: 'ru-RU',

    showPassword: 'Показать пароль',
    hidePassword: 'Скрыть пароль',

    allFolders: 'Все папки',
    selectedOf: 'Выбрано {n} из {total}',
    messagesUnit: 'писем',
    gbUnit: 'ГБ',

    serverResponded: 'сервер ответил {status}',
    noJobId: 'сервер не вернул идентификатор задания',
    connectionOk: 'Подключение успешно',
    checking: 'Проверяем…',

    strictEnable: 'Включить',
    strictDisable: 'Выключить',
    strictTitleOn: 'Строгое зеркало включено — лишние письма в назначении будут удалены',
    strictTitleOff: 'Строгое зеркало — разрушающая опция',
    confirmTitle: 'Это удалит письма в новом ящике',
    confirmTextA: 'Строгое зеркало приводит назначение к точной копии источника: всё, чего нет в старом ящике, будет ',
    confirmTextStrong: 'безвозвратно удалено',
    confirmTextB: ' в новом. Включайте только если понимаете, зачем это вам.',
    confirmAck: 'Я понимаю, что письма в ящике назначения будут удалены, и у меня есть резервная копия',
    confirmNo: 'Оставить безопасный режим',
    confirmYes: 'Включить зеркало',

    startDefault: 'Запустить перенос',
    modeVerboseBtn: 'Запустить в режиме проверки',
    modeVerboseHint: 'Только подробный вывод — ничего не копируется',
    modeCredsBtn: 'Проверить доступы',
    modeCredsHint: 'Только проверка TLS и авторизации',
    modeSizesBtn: 'Показать размеры папок',
    modeSizesHint: 'Только подсчёт дерева папок и объёма',
    modeFoldersBtn: 'Создать структуру папок',
    modeFoldersHint: 'Только создание папок в назначении',

    statusRunning: 'Выполняется',
    statusDone: 'Завершено',
    statusError: 'Ошибка',
    statusStopped: 'Остановлено',
    transferFailed: 'Перенос прерван из-за ошибки',
    stoppedLog: 'Остановлено. Повторный запуск продолжит с этого места.',

    /* --- список папок (реальные имена с сервера, без размеров) --- */
    foldersLoad: 'Показать папки источника',
    foldersLoading: 'Запрашиваем список папок…',
    foldersFailed: 'Не удалось получить список папок: {message}',
    foldersNone: 'Источник не вернул ни одной папки',
    foldersLoaded: 'Получено папок: {n}',
    foldersNeedCreds: 'Заполните сервер, логин и пароль источника',
    selectAll: 'Выбрать все',
    selectNone: 'Снять все',
    selectedNothing: 'Ничего не выбрано',
    startNeedsFolders: 'Выберите хотя бы одну папку или снимите загруженный список — пустой выбор сервер не примет',

    /* --- прогресс и статусы --- */
    statusQueued: 'В очереди',
    statusCancelling: 'Останавливаем…',
    statusCancelled: 'Отменено',
    phaseIdle: 'Задание не запущено',
    phaseQueued: 'В очереди',
    phaseConnecting: 'Подключение',
    phasePreparing: 'Подготовка',
    phaseEstimating: 'Оценка объёма',
    phaseScanning: 'Чтение структуры',
    phaseCopying: 'Копирование',
    phaseVerifying: 'Сверка',
    phaseCompleted: 'Завершено',
    phaseCancelled: 'Отменено',
    phaseFailed: 'Ошибка',
    folderLabel: 'Папка',
    noValue: '—',
    bytesUnits: 'Б,КБ,МБ,ГБ,ТБ',
    speedLabel: 'скорость',
    perSecond: '/с',
    messagesShort: 'пис',
    minuteShort: 'мин',
    measured: 'измерено',

    /* --- поток событий и восстановление --- */
    streamLost: 'Связь с журналом потеряна — переподключаемся. Перенос продолжается на сервере.',
    streamBack: 'Связь с журналом восстановлена',
    restored: 'Продолжаем задание, запущенное в этой вкладке',
    jobGone: 'Прошлое задание больше недоступно — запустите новое',
    cancelRequested: 'Остановка запрошена. Ждём подтверждения от сервера — не закрывайте вкладку.',
    finishedCancelled: 'Задание отменено. Уже перенесённые письма остались в ящике назначения.',
    finishedFailed: 'Задание завершилось ошибкой',

    /* --- сопоставление ошибок API --- */
    errTooMany: 'Сервис занят: слишком много запросов. Повторите через минуту.',
    errUnavailable: 'Сервис временно недоступен. Попробуйте позже.',
    errForbidden: 'Сессия истекла или не подтверждена. Обновите страницу и повторите.',
    errNetwork: 'Сеть недоступна — запрос не дошёл до сервера',
  },
  en: {
    offlineStatus: 'Online transfer is not live yet — the check is unavailable',
    numberLocale: 'en-US',

    showPassword: 'Show password',
    hidePassword: 'Hide password',

    allFolders: 'All folders',
    selectedOf: 'Selected {n} of {total}',
    messagesUnit: 'messages',
    gbUnit: 'GB',

    serverResponded: 'the server answered {status}',
    noJobId: 'the server returned no job id',
    connectionOk: 'Connection succeeded',
    checking: 'Checking…',

    strictEnable: 'Enable',
    strictDisable: 'Disable',
    strictTitleOn: 'Strict mirror is on — extra messages on the destination will be deleted',
    strictTitleOff: 'Strict mirror — a destructive option',
    confirmTitle: 'This will delete mail in the new mailbox',
    confirmTextA: 'Strict mirror makes the destination an exact copy of the source: anything missing from the old mailbox will be ',
    confirmTextStrong: 'permanently deleted',
    confirmTextB: ' in the new one. Turn this on only if you know why you need it.',
    confirmAck: 'I understand that messages in the destination mailbox will be deleted, and I have a backup',
    confirmNo: 'Keep the safe mode',
    confirmYes: 'Enable the mirror',

    startDefault: 'Start the transfer',
    modeVerboseBtn: 'Run in check mode',
    modeVerboseHint: 'Verbose output only — nothing is copied',
    modeCredsBtn: 'Check credentials',
    modeCredsHint: 'TLS and authentication check only',
    modeSizesBtn: 'Show folder sizes',
    modeSizesHint: 'Folder tree and volume count only',
    modeFoldersBtn: 'Create the folder structure',
    modeFoldersHint: 'Creates folders on the destination only',

    statusRunning: 'Running',
    statusDone: 'Finished',
    statusError: 'Error',
    statusStopped: 'Stopped',
    transferFailed: 'The transfer stopped on an error',
    stoppedLog: 'Stopped. Running it again resumes from here.',

    /* --- folder list (real names from the server, no sizes) --- */
    foldersLoad: 'Show source folders',
    foldersLoading: 'Requesting the folder list…',
    foldersFailed: 'Could not get the folder list: {message}',
    foldersNone: 'The source returned no folders',
    foldersLoaded: 'Folders received: {n}',
    foldersNeedCreds: 'Fill in the source server, login and password',
    selectAll: 'Select all',
    selectNone: 'Clear all',
    selectedNothing: 'Nothing selected',
    startNeedsFolders: 'Select at least one folder, or drop the loaded list — the server will not accept an empty selection',

    /* --- progress and statuses --- */
    statusQueued: 'Queued',
    statusCancelling: 'Stopping…',
    statusCancelled: 'Cancelled',
    phaseIdle: 'No job running',
    phaseQueued: 'Queued',
    phaseConnecting: 'Connecting',
    phasePreparing: 'Preparing',
    phaseEstimating: 'Estimating',
    phaseScanning: 'Reading the structure',
    phaseCopying: 'Copying',
    phaseVerifying: 'Verifying',
    phaseCompleted: 'Finished',
    phaseCancelled: 'Cancelled',
    phaseFailed: 'Failed',
    folderLabel: 'Folder',
    noValue: '—',
    bytesUnits: 'B,KB,MB,GB,TB',
    speedLabel: 'rate',
    perSecond: '/s',
    messagesShort: 'msg',
    minuteShort: 'min',
    measured: 'measured',

    /* --- event stream and recovery --- */
    streamLost: 'Lost the log connection — reconnecting. The transfer keeps running on the server.',
    streamBack: 'Log connection restored',
    restored: 'Resuming the job started in this tab',
    jobGone: 'The previous job is no longer available — start a new one',
    cancelRequested: 'Stop requested. Waiting for the server to confirm — keep this tab open.',
    finishedCancelled: 'The job was cancelled. Messages already transferred stay in the destination mailbox.',
    finishedFailed: 'The job ended with an error',

    /* --- API error mapping --- */
    errTooMany: 'The service is busy: too many requests. Try again in a minute.',
    errUnavailable: 'The service is temporarily unavailable. Try again later.',
    errForbidden: 'The session expired or was not confirmed. Reload the page and try again.',
    errNetwork: 'No network — the request never reached the server',
  },
  uk: {
    offlineStatus: 'Онлайн-перенесення ще не запущене — перевірка недоступна',
    numberLocale: 'uk-UA',

    showPassword: 'Показати пароль',
    hidePassword: 'Сховати пароль',

    allFolders: 'Усі папки',
    selectedOf: 'Вибрано {n} з {total}',
    messagesUnit: 'листів',
    gbUnit: 'ГБ',

    serverResponded: 'сервер відповів {status}',
    noJobId: 'сервер не повернув ідентифікатор завдання',
    connectionOk: 'З’єднання встановлено',
    checking: 'Перевіряємо…',

    strictEnable: 'Увімкнути',
    strictDisable: 'Вимкнути',
    strictTitleOn: 'Суворе дзеркало увімкнено — зайві листи у призначенні буде видалено',
    strictTitleOff: 'Суворе дзеркало — руйнівна опція',
    confirmTitle: 'Це видалить листи в новій скриньці',
    confirmTextA: 'Суворе дзеркало робить призначення точною копією джерела: усе, чого немає в старій скриньці, буде ',
    confirmTextStrong: 'безповоротно видалено',
    confirmTextB: ' у новій. Вмикайте лише якщо розумієте, навіщо це вам.',
    confirmAck: 'Я розумію, що листи у скриньці призначення буде видалено, і в мене є резервна копія',
    confirmNo: 'Залишити безпечний режим',
    confirmYes: 'Увімкнути дзеркало',

    startDefault: 'Запустити перенесення',
    modeVerboseBtn: 'Запустити в режимі перевірки',
    modeVerboseHint: 'Лише докладний вивід — нічого не копіюється',
    modeCredsBtn: 'Перевірити доступи',
    modeCredsHint: 'Лише перевірка TLS та авторизації',
    modeSizesBtn: 'Показати розміри папок',
    modeSizesHint: 'Лише підрахунок дерева папок і обсягу',
    modeFoldersBtn: 'Створити структуру папок',
    modeFoldersHint: 'Лише створення папок у призначенні',

    statusRunning: 'Виконується',
    statusDone: 'Завершено',
    statusError: 'Помилка',
    statusStopped: 'Зупинено',
    transferFailed: 'Перенесення перервано через помилку',
    stoppedLog: 'Зупинено. Повторний запуск продовжить з цього місця.',

    /* --- список папок (справжні імена із сервера, без розмірів) --- */
    foldersLoad: 'Показати папки джерела',
    foldersLoading: 'Запитуємо список папок…',
    foldersFailed: 'Не вдалося отримати список папок: {message}',
    foldersNone: 'Джерело не повернуло жодної папки',
    foldersLoaded: 'Отримано папок: {n}',
    foldersNeedCreds: 'Заповніть сервер, логін і пароль джерела',
    selectAll: 'Вибрати всі',
    selectNone: 'Зняти всі',
    selectedNothing: 'Нічого не вибрано',
    startNeedsFolders: 'Виберіть хоча б одну папку або скиньте завантажений список — порожній вибір сервер не прийме',

    /* --- прогрес і статуси --- */
    statusQueued: 'У черзі',
    statusCancelling: 'Зупиняємо…',
    statusCancelled: 'Скасовано',
    phaseIdle: 'Завдання не запущене',
    phaseQueued: 'У черзі',
    phaseConnecting: 'Підключення',
    phasePreparing: 'Підготовка',
    phaseEstimating: 'Оцінка обсягу',
    phaseScanning: 'Читання структури',
    phaseCopying: 'Копіювання',
    phaseVerifying: 'Звірка',
    phaseCompleted: 'Завершено',
    phaseCancelled: 'Скасовано',
    phaseFailed: 'Помилка',
    folderLabel: 'Папка',
    noValue: '—',
    bytesUnits: 'Б,КБ,МБ,ГБ,ТБ',
    speedLabel: 'швидкість',
    perSecond: '/с',
    messagesShort: 'лист',
    minuteShort: 'хв',
    measured: 'виміряно',

    /* --- потік подій і відновлення --- */
    streamLost: 'Зв’язок із журналом втрачено — перепідключаємось. Перенесення триває на сервері.',
    streamBack: 'Зв’язок із журналом відновлено',
    restored: 'Продовжуємо завдання, запущене в цій вкладці',
    jobGone: 'Попереднє завдання більше недоступне — запустіть нове',
    cancelRequested: 'Зупинку запрошено. Чекаємо на підтвердження від сервера — не закривайте вкладку.',
    finishedCancelled: 'Завдання скасовано. Уже перенесені листи залишилися у скриньці призначення.',
    finishedFailed: 'Завдання завершилося помилкою',

    /* --- зіставлення помилок API --- */
    errTooMany: 'Сервіс зайнятий: забагато запитів. Повторіть за хвилину.',
    errUnavailable: 'Сервіс тимчасово недоступний. Спробуйте пізніше.',
    errForbidden: 'Сесія завершилася або не підтверджена. Оновіть сторінку та повторіть.',
    errNetwork: 'Мережа недоступна — запит не дійшов до сервера',
  },
} as const;
