/** Копия разметки рабочей области. Один файл на секцию — три языка рядом.
 * Строки, которые подставляет императивный код, лежат в workspace-runtime.ts. */
export const workspace = {
  ru: {
    staticPasswordPlaceholder: 'Онлайн-перенос пока недоступен',
    previewNoticeA: 'Онлайн-перенос готовится к запуску. Здесь показан интерфейс: ввод данных и отправка запросов отключены. Для переноса сейчас используйте ',
    previewNoticeLink: 'локальный клиент',
    previewNoticeB: '.',
    title: 'Рабочая область переноса',
    chip: 'IMAP → IMAP',

    srcSmall: 'Откуда',
    srcTitle: 'Источник',
    dstSmall: 'Куда',
    dstTitle: 'Назначение',
    notChecked: 'Не проверено',

    hostLabel: 'IMAP-сервер или IP-адрес',
    srcHostPlaceholder: 'imap.old-company.com / 203.0.113.10',
    dstHostPlaceholder: 'imap.new-company.com / 203.0.113.20',
    loginLabel: 'Логин почтового ящика',
    loginPlaceholder: 'Например: name@example.com',
    passwordLabel: 'Пароль или пароль приложения',
    passwordPlaceholder: 'Введите пароль',
    showPassword: 'Показать пароль',

    connSettings: 'Настройки подключения',
    connSettingsHint: 'Автоматически — рекомендуется',
    securityLabel: 'Безопасность',
    portLabel: 'Порт',
    portAuto: 'Автоматически · 993',
    portManual: 'Указать вручную',
    subfolderLabel: 'Подпапка назначения — необязательно',
    subfolderPlaceholder: 'Например: Архив/Старый ящик',

    swap: 'Поменять ящики местами',
    checkBoth: 'Проверить оба',
    linkProviders: 'Настройки провайдеров',
    linkErrors: 'Ошибки IMAP',

    assureSource: 'Источник не удаляется',
    assureSize: 'Объём считается до запуска',
    start: 'Запустить перенос',
    stop: 'Остановить',

    foldersTitle: 'Папки для переноса',
    foldersSum: 'Все папки · 41 208 писем · 12.4 ГБ',
    sizeInbox: '5.9 ГБ',
    sizeSent: '3.1 ГБ',
    sizeArchive: '2.9 ГБ',
    sizeInvoices: '412 МБ',
    sizeJunk: '88 МБ',

    advTitle: 'Расширенные настройки',
    advSum: 'Режимы запуска · строгое зеркало',
    modeVerboseTitle: 'Только подробный вывод',
    modeVerboseTextA: 'Пройти весь сценарий и показать журнал, ничего не копируя. Аналог ',
    modeVerboseTextB: '.',
    modeCredsTitle: 'Только проверить доступы',
    modeCredsText: 'Подключиться, проверить TLS и авторизацию на обеих сторонах и выйти.',
    modeSizesTitle: 'Только показать размеры папок',
    modeSizesText: 'Посчитать дерево папок, письма и объём — чтобы узнать цену до запуска.',
    modeFoldersTitle: 'Только создать папки',
    modeFoldersTextA: 'Создать структуру папок в назначении, не перенося письма. Аналог ',
    modeFoldersTextB: '.',

    strictTitle: 'Строгое зеркало — разрушающая опция',
    strictText: 'Удаляет в назначении письма, которых нет в источнике. По умолчанию выключено: базовый режим только копирует.',
    strictBtn: 'Включить',

    keepBold: 'Источник не изменяется: базовый режим только копирует.',
    keepText: 'Учётные данные шифруются перед постановкой в очередь, открытый пароль не сохраняется. Не хотите отдавать пароль вообще — настольный клиент и Docker работают без нашей инфраструктуры.',
    keepLink: 'Забрать клиент →',
    freeNote: 'Бесплатно переносится один целый ящик объёмом до 5 ГБ. Для большего объёма тариф выбирается после замера.',

    logTitle: 'Журнал переноса',
    logSub: 'Папка за папкой, в реальном времени',
    statusWaiting: 'Ожидание',
    metricProgress: 'Прогресс',
    metricLeft: 'Осталось',
    metricSpeed: 'Скорость',
    speedUnit: 'пис/с',
    logFirst: 'Подключите оба ящика и нажмите «Проверить оба».',
    logFoot: 'Каждая папка, счётчики с обеих сторон и причина по каждому пропущенному письму.',
  },
  en: {
    staticPasswordPlaceholder: 'Online transfer is not live yet',
    previewNoticeA: 'Online transfer is getting ready for launch. What you see here is the interface: data entry and outgoing requests are disabled. To move mail right now, use the ',
    previewNoticeLink: 'local client',
    previewNoticeB: '.',
    title: 'Transfer workspace',
    chip: 'IMAP → IMAP',

    srcSmall: 'From',
    srcTitle: 'Source',
    dstSmall: 'To',
    dstTitle: 'Destination',
    notChecked: 'Not checked',

    hostLabel: 'IMAP server or IP address',
    srcHostPlaceholder: 'imap.old-company.com / 203.0.113.10',
    dstHostPlaceholder: 'imap.new-company.com / 203.0.113.20',
    loginLabel: 'Mailbox login',
    loginPlaceholder: 'For example: name@example.com',
    passwordLabel: 'Password or app password',
    passwordPlaceholder: 'Enter the password',
    showPassword: 'Show password',

    connSettings: 'Connection settings',
    connSettingsHint: 'Automatic — recommended',
    securityLabel: 'Security',
    portLabel: 'Port',
    portAuto: 'Automatic · 993',
    portManual: 'Set manually',
    subfolderLabel: 'Destination subfolder — optional',
    subfolderPlaceholder: 'For example: Archive/Old mailbox',

    swap: 'Swap the mailboxes',
    checkBoth: 'Check both',
    linkProviders: 'Provider settings',
    linkErrors: 'IMAP errors',

    assureSource: 'Source is never deleted',
    assureSize: 'Size is measured before the run',
    start: 'Start the transfer',
    stop: 'Stop',

    foldersTitle: 'Folders to transfer',
    foldersSum: 'All folders · 41,208 messages · 12.4 GB',
    sizeInbox: '5.9 GB',
    sizeSent: '3.1 GB',
    sizeArchive: '2.9 GB',
    sizeInvoices: '412 MB',
    sizeJunk: '88 MB',

    advTitle: 'Advanced settings',
    advSum: 'Run modes · strict mirror',
    modeVerboseTitle: 'Verbose output only',
    modeVerboseTextA: 'Walk through the whole run and show the log without copying anything. Same as ',
    modeVerboseTextB: '.',
    modeCredsTitle: 'Check credentials only',
    modeCredsText: 'Connect, verify TLS and authentication on both sides, then exit.',
    modeSizesTitle: 'Show folder sizes only',
    modeSizesText: 'Count the folder tree, messages and volume — so you know the price before starting.',
    modeFoldersTitle: 'Create folders only',
    modeFoldersTextA: 'Build the folder structure on the destination without moving messages. Same as ',
    modeFoldersTextB: '.',

    strictTitle: 'Strict mirror — a destructive option',
    strictText: 'Deletes messages on the destination that are missing from the source. Off by default: the base mode only copies.',
    strictBtn: 'Enable',

    keepBold: 'The source is left untouched: the base mode only copies.',
    keepText: 'Credentials are encrypted before the job is queued, and the plaintext password is never stored. If you would rather not hand over the password at all, the desktop client and Docker run without our infrastructure.',
    keepLink: 'Get the client →',
    freeNote: 'One full mailbox of up to 5 GB transfers free. Above that, the plan is chosen after the size check.',

    logTitle: 'Transfer log',
    logSub: 'Folder by folder, in real time',
    statusWaiting: 'Idle',
    metricProgress: 'Progress',
    metricLeft: 'Remaining',
    metricSpeed: 'Speed',
    speedUnit: 'msg/s',
    logFirst: 'Connect both mailboxes and press “Check both”.',
    logFoot: 'Every folder, counts from both sides, and a reason for each skipped message.',
  },
  uk: {
    staticPasswordPlaceholder: 'Онлайн-перенесення поки недоступне',
    previewNoticeA: 'Онлайн-перенесення готується до запуску. Тут показано інтерфейс: введення даних і надсилання запитів вимкнено. Для перенесення зараз скористайтеся ',
    previewNoticeLink: 'локальним клієнтом',
    previewNoticeB: '.',
    title: 'Робоча область перенесення',
    chip: 'IMAP → IMAP',

    srcSmall: 'Звідки',
    srcTitle: 'Джерело',
    dstSmall: 'Куди',
    dstTitle: 'Призначення',
    notChecked: 'Не перевірено',

    hostLabel: 'IMAP-сервер або IP-адреса',
    srcHostPlaceholder: 'imap.old-company.com / 203.0.113.10',
    dstHostPlaceholder: 'imap.new-company.com / 203.0.113.20',
    loginLabel: 'Логін поштової скриньки',
    loginPlaceholder: 'Наприклад: name@example.com',
    passwordLabel: 'Пароль або пароль застосунку',
    passwordPlaceholder: 'Введіть пароль',
    showPassword: 'Показати пароль',

    connSettings: 'Налаштування підключення',
    connSettingsHint: 'Автоматично — рекомендовано',
    securityLabel: 'Безпека',
    portLabel: 'Порт',
    portAuto: 'Автоматично · 993',
    portManual: 'Вказати вручну',
    subfolderLabel: 'Підпапка призначення — необов’язково',
    subfolderPlaceholder: 'Наприклад: Архів/Стара скринька',

    swap: 'Поміняти скриньки місцями',
    checkBoth: 'Перевірити обидві',
    linkProviders: 'Налаштування провайдерів',
    linkErrors: 'Помилки IMAP',

    assureSource: 'Джерело не видаляється',
    assureSize: 'Обсяг рахується до запуску',
    start: 'Запустити перенесення',
    stop: 'Зупинити',

    foldersTitle: 'Папки для перенесення',
    foldersSum: 'Усі папки · 41 208 листів · 12.4 ГБ',
    sizeInbox: '5.9 ГБ',
    sizeSent: '3.1 ГБ',
    sizeArchive: '2.9 ГБ',
    sizeInvoices: '412 МБ',
    sizeJunk: '88 МБ',

    advTitle: 'Розширені налаштування',
    advSum: 'Режими запуску · суворе дзеркало',
    modeVerboseTitle: 'Лише докладний вивід',
    modeVerboseTextA: 'Пройти весь сценарій і показати журнал, нічого не копіюючи. Аналог ',
    modeVerboseTextB: '.',
    modeCredsTitle: 'Лише перевірити доступи',
    modeCredsText: 'Підключитися, перевірити TLS та авторизацію з обох боків і вийти.',
    modeSizesTitle: 'Лише показати розміри папок',
    modeSizesText: 'Порахувати дерево папок, листи та обсяг — щоб дізнатися ціну до запуску.',
    modeFoldersTitle: 'Лише створити папки',
    modeFoldersTextA: 'Створити структуру папок у призначенні, не переносячи листи. Аналог ',
    modeFoldersTextB: '.',

    strictTitle: 'Суворе дзеркало — руйнівна опція',
    strictText: 'Видаляє у призначенні листи, яких немає в джерелі. Типово вимкнено: базовий режим лише копіює.',
    strictBtn: 'Увімкнути',

    keepBold: 'Джерело не змінюється: базовий режим лише копіює.',
    keepText: 'Облікові дані шифруються перед постановкою в чергу, відкритий пароль не зберігається. Не хочете віддавати пароль взагалі — настільний клієнт і Docker працюють без нашої інфраструктури.',
    keepLink: 'Забрати клієнт →',
    freeNote: 'Безкоштовно переноситься одна ціла скринька обсягом до 5 ГБ. Для більшого обсягу тариф обирається після заміру.',

    logTitle: 'Журнал перенесення',
    logSub: 'Папка за папкою, у реальному часі',
    statusWaiting: 'Очікування',
    metricProgress: 'Прогрес',
    metricLeft: 'Залишилось',
    metricSpeed: 'Швидкість',
    speedUnit: 'лист/с',
    logFirst: 'Підключіть обидві скриньки та натисніть «Перевірити обидві».',
    logFoot: 'Кожна папка, лічильники з обох боків і причина щодо кожного пропущеного листа.',
  },
} as const;
