/** Строки, которые подставляет императивный код рабочей области (lib/workspace.ts):
 * статусы, кнопки режимов, сообщения журнала и модалка строгого зеркала.
 * Разметка секции переведена отдельно — в workspace.ts. */
export const workspaceRuntime = {
  ru: {
    offlineStatus: 'Онлайн-перенос ещё не запущен — проверка недоступна',
    numberLocale: 'ru-RU',

    showPassword: 'Показать пароль',
    hidePassword: 'Скрыть пароль',

    allFolders: 'Все папки',
    selectedOf: 'Выбрано {n} из {total}',
    messagesUnit: 'писем',
    gbUnit: 'ГБ',

    serverResponded: 'сервер ответил {status}',
    noJobId: 'сервер не вернул идентификатор задания',
    connectionOk: 'Подключение успешно',
    checking: 'Проверяем…',

    strictEnable: 'Включить',
    strictDisable: 'Выключить',
    strictTitleOn: 'Строгое зеркало включено — лишние письма в назначении будут удалены',
    strictTitleOff: 'Строгое зеркало — разрушающая опция',
    confirmTitle: 'Это удалит письма в новом ящике',
    confirmTextA: 'Строгое зеркало приводит назначение к точной копии источника: всё, чего нет в старом ящике, будет ',
    confirmTextStrong: 'безвозвратно удалено',
    confirmTextB: ' в новом. Включайте только если понимаете, зачем это вам.',
    confirmAck: 'Я понимаю, что письма в ящике назначения будут удалены, и у меня есть резервная копия',
    confirmNo: 'Оставить безопасный режим',
    confirmYes: 'Включить зеркало',

    startDefault: 'Запустить перенос',
    modeVerboseBtn: 'Запустить в режиме проверки',
    modeVerboseHint: 'Только подробный вывод — ничего не копируется',
    modeCredsBtn: 'Проверить доступы',
    modeCredsHint: 'Только проверка TLS и авторизации',
    modeSizesBtn: 'Показать размеры папок',
    modeSizesHint: 'Только подсчёт дерева папок и объёма',
    modeFoldersBtn: 'Создать структуру папок',
    modeFoldersHint: 'Только создание папок в назначении',

    statusRunning: 'Выполняется',
    statusDone: 'Завершено',
    statusError: 'Ошибка',
    statusStopped: 'Остановлено',
    speedUnit: 'пис/с',
    transferFailed: 'Перенос прерван из-за ошибки',
    stoppedLog: 'Остановлено. Повторный запуск продолжит с этого места.',
  },
  en: {
    offlineStatus: 'Online transfer is not live yet — the check is unavailable',
    numberLocale: 'en-US',

    showPassword: 'Show password',
    hidePassword: 'Hide password',

    allFolders: 'All folders',
    selectedOf: 'Selected {n} of {total}',
    messagesUnit: 'messages',
    gbUnit: 'GB',

    serverResponded: 'the server answered {status}',
    noJobId: 'the server returned no job id',
    connectionOk: 'Connection succeeded',
    checking: 'Checking…',

    strictEnable: 'Enable',
    strictDisable: 'Disable',
    strictTitleOn: 'Strict mirror is on — extra messages on the destination will be deleted',
    strictTitleOff: 'Strict mirror — a destructive option',
    confirmTitle: 'This will delete mail in the new mailbox',
    confirmTextA: 'Strict mirror makes the destination an exact copy of the source: anything missing from the old mailbox will be ',
    confirmTextStrong: 'permanently deleted',
    confirmTextB: ' in the new one. Turn this on only if you know why you need it.',
    confirmAck: 'I understand that messages in the destination mailbox will be deleted, and I have a backup',
    confirmNo: 'Keep the safe mode',
    confirmYes: 'Enable the mirror',

    startDefault: 'Start the transfer',
    modeVerboseBtn: 'Run in check mode',
    modeVerboseHint: 'Verbose output only — nothing is copied',
    modeCredsBtn: 'Check credentials',
    modeCredsHint: 'TLS and authentication check only',
    modeSizesBtn: 'Show folder sizes',
    modeSizesHint: 'Folder tree and volume count only',
    modeFoldersBtn: 'Create the folder structure',
    modeFoldersHint: 'Creates folders on the destination only',

    statusRunning: 'Running',
    statusDone: 'Finished',
    statusError: 'Error',
    statusStopped: 'Stopped',
    speedUnit: 'msg/s',
    transferFailed: 'The transfer stopped on an error',
    stoppedLog: 'Stopped. Running it again resumes from here.',
  },
  uk: {
    offlineStatus: 'Онлайн-перенесення ще не запущене — перевірка недоступна',
    numberLocale: 'uk-UA',

    showPassword: 'Показати пароль',
    hidePassword: 'Сховати пароль',

    allFolders: 'Усі папки',
    selectedOf: 'Вибрано {n} з {total}',
    messagesUnit: 'листів',
    gbUnit: 'ГБ',

    serverResponded: 'сервер відповів {status}',
    noJobId: 'сервер не повернув ідентифікатор завдання',
    connectionOk: 'З’єднання встановлено',
    checking: 'Перевіряємо…',

    strictEnable: 'Увімкнути',
    strictDisable: 'Вимкнути',
    strictTitleOn: 'Суворе дзеркало увімкнено — зайві листи у призначенні буде видалено',
    strictTitleOff: 'Суворе дзеркало — руйнівна опція',
    confirmTitle: 'Це видалить листи в новій скриньці',
    confirmTextA: 'Суворе дзеркало робить призначення точною копією джерела: усе, чого немає в старій скриньці, буде ',
    confirmTextStrong: 'безповоротно видалено',
    confirmTextB: ' у новій. Вмикайте лише якщо розумієте, навіщо це вам.',
    confirmAck: 'Я розумію, що листи у скриньці призначення буде видалено, і в мене є резервна копія',
    confirmNo: 'Залишити безпечний режим',
    confirmYes: 'Увімкнути дзеркало',

    startDefault: 'Запустити перенесення',
    modeVerboseBtn: 'Запустити в режимі перевірки',
    modeVerboseHint: 'Лише докладний вивід — нічого не копіюється',
    modeCredsBtn: 'Перевірити доступи',
    modeCredsHint: 'Лише перевірка TLS та авторизації',
    modeSizesBtn: 'Показати розміри папок',
    modeSizesHint: 'Лише підрахунок дерева папок і обсягу',
    modeFoldersBtn: 'Створити структуру папок',
    modeFoldersHint: 'Лише створення папок у призначенні',

    statusRunning: 'Виконується',
    statusDone: 'Завершено',
    statusError: 'Помилка',
    statusStopped: 'Зупинено',
    speedUnit: 'лист/с',
    transferFailed: 'Перенесення перервано через помилку',
    stoppedLog: 'Зупинено. Повторний запуск продовжить з цього місця.',
  },
} as const;
