/** Обвязка страницы разбора ошибки IMAP. */
export const errorPage = {
  ru: {
    home: 'Главная',
    errors: 'Ошибки',
    eyebrow: 'Диагностика IMAP',
    sample: 'Как выглядит в журнале',
    causesA: 'Причины,',
    causesB: 'по убыванию вероятности',
    fixes: 'Что сделать',
    cta: 'Проверить подключение в MoveMailbox',
    faqEyebrow: 'FAQ',
    faqTitle: 'Частые вопросы',
    others: 'Другие ошибки',
  },
  en: {
    home: 'Home',
    errors: 'Errors',
    eyebrow: 'IMAP diagnostics',
    sample: 'How it looks in the log',
    causesA: 'Causes,',
    causesB: 'most likely first',
    fixes: 'How to fix it',
    cta: 'Test the connection in MoveMailbox',
    faqEyebrow: 'FAQ',
    faqTitle: 'Common questions',
    others: 'Other errors',
  },
  uk: {
    home: 'Головна',
    errors: 'Помилки',
    eyebrow: 'Діагностика IMAP',
    sample: 'Як виглядає в журналі',
    causesA: 'Причини,',
    causesB: 'за спаданням імовірності',
    fixes: 'Що зробити',
    cta: 'Перевірити підключення в MoveMailbox',
    faqEyebrow: 'FAQ',
    faqTitle: 'Часті питання',
    others: 'Інші помилки',
  },
} as const;
