/** Обвязка страницы провайдера: заголовки блоков, не сам контент.
 *  Сам контент — в data/provider-hubs.ts, по одному тексту на язык. */
export const providerHubPage = {
  ru: {
    eyebrow: 'Провайдер',
    rowServer: 'Сервер IMAP',
    rowPort: 'Порт',
    rowLogin: 'Логин',
    rowPassword: 'Пароль',
    loginEmail: 'полный адрес почты',
    loginLocal: 'часть до @, без домена',
    passwordApp: 'пароль приложения',
    passwordPlain: 'пароль от ящика',
    settingsTitle: 'Настройки подключения',
    settingsLede: 'То же самое подставляется в форму автоматически, когда вы выбираете провайдера.',
    genericTitle: 'Где взять настройки',
    genericLede:
      'У своего сервера параметры смотрят в панели хостинга — раздел «Почта → Настройка клиента». Форма принимает и имя сервера, и IP-адрес.',
    genericRows: [
      ['Сервер', 'imap.домен или mail.домен, либо IP-адрес'],
      ['Порт', '993 — SSL/TLS, 143 — STARTTLS'],
      ['Логин', 'чаще полный адрес, иногда user@domain или user'],
      ['Пароль', 'от ящика; у крупных сервисов — пароль приложения'],
    ] as Array<[string, string]>,
    pitfallsA: 'Что ломает перенос',
    pitfallsB: 'именно здесь',
    routesTitle: 'Куда переносят чаще всего',
    routesLede: 'Готовые страницы с настройками обеих сторон и порядком действий.',
    routesAll: 'Все маршруты',
    faqEyebrow: 'FAQ',
    faqTitle: 'Частые вопросы',
    cta: (name: string) => `Перенести почту ${name}`,
    steps: {
      check: 'Проверить доступ',
      checkText: (name: string, app: boolean) =>
        `Включите IMAP в ${name} и подготовьте ${app ? 'пароль приложения' : 'пароль от ящика'}.`,
      dest: 'Подготовить второй ящик',
      destText: 'Создайте ящик у нового провайдера и убедитесь, что места хватает под весь объём.',
      folders: 'Выбрать папки',
      foldersText: 'Получите список папок с сервера и снимите отметки со спама и корзины.',
      run: 'Запустить и сверить',
      runText: 'Запустите перенос и сверьте счётчики писем по папкам с обеих сторон.',
    },
  },
  en: {
    eyebrow: 'Provider',
    rowServer: 'IMAP server',
    rowPort: 'Port',
    rowLogin: 'Username',
    rowPassword: 'Password',
    loginEmail: 'the full email address',
    loginLocal: 'the part before @, no domain',
    passwordApp: 'an app password',
    passwordPlain: 'the mailbox password',
    settingsTitle: 'Connection settings',
    settingsLede: 'The form fills these in for you as soon as you pick the provider.',
    genericTitle: 'Where to find the settings',
    genericLede:
      'For your own server the values live in the hosting panel, under "Mail → client configuration". The form accepts a hostname or an IP address.',
    genericRows: [
      ['Server', 'imap.yourdomain or mail.yourdomain, or an IP address'],
      ['Port', '993 for SSL/TLS, 143 for STARTTLS'],
      ['Username', 'usually the full address, sometimes user@domain or user'],
      ['Password', 'the mailbox password; large services need an app password'],
    ] as Array<[string, string]>,
    pitfallsA: 'What breaks a migration',
    pitfallsB: 'here specifically',
    routesTitle: 'Where mailboxes go from here',
    routesLede: 'Ready pages with the settings for both sides and the order of steps.',
    routesAll: 'All routes',
    faqEyebrow: 'FAQ',
    faqTitle: 'Common questions',
    cta: (name: string) => `Migrate ${name} mail`,
    steps: {
      check: 'Check access',
      checkText: (name: string, app: boolean) =>
        `Enable IMAP in ${name} and prepare ${app ? 'an app password' : 'the mailbox password'}.`,
      dest: 'Prepare the second mailbox',
      destText: 'Create the mailbox at the new provider and make sure it has room for the whole volume.',
      folders: 'Pick the folders',
      foldersText: 'Load the folder list from the server and clear spam and trash.',
      run: 'Run it and reconcile',
      runText: 'Start the transfer and compare the per-folder message counts on both sides.',
    },
  },
  uk: {
    eyebrow: 'Провайдер',
    rowServer: 'Сервер IMAP',
    rowPort: 'Порт',
    rowLogin: 'Логін',
    rowPassword: 'Пароль',
    loginEmail: 'повна адреса пошти',
    loginLocal: 'частина до @, без домену',
    passwordApp: 'пароль застосунку',
    passwordPlain: 'пароль від скриньки',
    settingsTitle: 'Налаштування підключення',
    settingsLede: 'Те саме форма підставляє автоматично, щойно ви обираєте провайдера.',
    genericTitle: 'Де взяти налаштування',
    genericLede:
      'Для власного сервера параметри дивляться в панелі хостингу — розділ «Пошта → Налаштування клієнта». Форма приймає і ім’я сервера, і IP-адресу.',
    genericRows: [
      ['Сервер', 'imap.домен або mail.домен, чи IP-адреса'],
      ['Порт', '993 — SSL/TLS, 143 — STARTTLS'],
      ['Логін', 'найчастіше повна адреса, іноді user@domain або user'],
      ['Пароль', 'від скриньки; у великих сервісів — пароль застосунку'],
    ] as Array<[string, string]>,
    pitfallsA: 'Що ламає перенесення',
    pitfallsB: 'саме тут',
    routesTitle: 'Куди переносять найчастіше',
    routesLede: 'Готові сторінки з налаштуваннями обох боків і порядком дій.',
    routesAll: 'Усі маршрути',
    faqEyebrow: 'FAQ',
    faqTitle: 'Часті питання',
    cta: (name: string) => `Перенести пошту ${name}`,
    steps: {
      check: 'Перевірити доступ',
      checkText: (name: string, app: boolean) =>
        `Увімкніть IMAP у ${name} і підготуйте ${app ? 'пароль застосунку' : 'пароль від скриньки'}.`,
      dest: 'Підготувати другу скриньку',
      destText: 'Створіть скриньку в нового провайдера і переконайтеся, що місця вистачає на весь обсяг.',
      folders: 'Обрати теки',
      foldersText: 'Отримайте список тек із сервера та зніміть позначки зі спаму й кошика.',
      run: 'Запустити та звірити',
      runText: 'Запустіть перенесення і звірте лічильники листів за теками з обох боків.',
    },
  },
} as const;
