/** Копия шапки сайта. Один файл — три языка рядом. */
export const siteHeader = {
  ru: {
    home: 'Главная',
    routes: 'Маршруты',
    guides: 'Провайдеры',
    pricing: 'Тарифы',
    blog: 'Блог',
    download: 'Скачать',
    langGroup: 'Язык',
    themeLight: 'Светлая тема',
    themeDark: 'Тёмная тема',
    cta: 'Скачать клиент',
    menu: 'Меню',
    mobNav: 'Мобильная навигация',
    security: 'Безопасность',
    errors: 'Ошибки IMAP',
  },
  en: {
    home: 'Home',
    routes: 'Routes',
    guides: 'Providers',
    pricing: 'Pricing',
    blog: 'Blog',
    download: 'Download',
    langGroup: 'Language',
    themeLight: 'Light theme',
    themeDark: 'Dark theme',
    cta: 'Download the client',
    menu: 'Menu',
    mobNav: 'Mobile navigation',
    security: 'Security',
    errors: 'IMAP errors',
  },
  uk: {
    home: 'Головна',
    routes: 'Маршрути',
    guides: 'Провайдери',
    pricing: 'Тарифи',
    blog: 'Блог',
    download: 'Завантажити',
    langGroup: 'Мова',
    themeLight: 'Світла тема',
    themeDark: 'Темна тема',
    cta: 'Завантажити клієнт',
    menu: 'Меню',
    mobNav: 'Мобільна навігація',
    security: 'Безпека',
    errors: 'Помилки IMAP',
  },
} as const;
